local api = ESV_SEMANTIC_DEFINITION_TEST_API

test("semantic definition splits top-level members without splitting expressions", function()
    local parts = api.split_top_level_text("SUM(a, b), RATIO(x, NULLIF(y, 0)), z")
    assert_equal(#parts, 3)
    assert_contains(parts[2], "NULLIF")
end)

test("semantic definition parses aggregate structure", function()
    local fn, expression = api.aggregate_parts("SUM(net_revenue)")
    assert_equal(fn, "SUM")
    assert_equal(expression, "net_revenue")
    local absent = api.aggregate_parts("gross_margin / revenue")
    assert_branch("definition.aggregate", fn ~= nil, true)
    assert_branch("definition.aggregate", absent ~= nil, false)
end)

test("Databricks helpers parse table references filters and measures", function()
    local schema, object = api.dbx_table_ref("catalog.sales.orders")
    assert_equal(schema, "SALES")
    assert_equal(object, "ORDERS")
    local measure = api.dbx_unwrap_measures("MEASURE(revenue) / MEASURE(units)")
    assert_equal(measure, "revenue / units")
    local aggregate, inner = api.dbx_aggregate("SUM(orders.amount)")
    assert_equal(aggregate, "SUM")
    assert_equal(inner, "orders.amount")
end)

test("semantic definition JSON round-trip supports escaped strings", function()
    local encoded = api.json_encode({name = "a\nb", values = {1, 2}})
    local decoded = api.json_decode(encoded)
    assert_equal(decoded.name, "a\nb")
    assert_equal(decoded.values[2], 2)
end)
