SELECT *
FROM SEMANTIC_CATALOG.MODELS
WHERE MODEL_NAME = 'sales';

SELECT OBJECT_NAME, COLUMN_NAME, COLUMN_KIND, ORDINAL_POSITION, DISPLAY_NAME
FROM SEMANTIC_CATALOG.OBJECT_COLUMNS
WHERE MODEL_NAME = 'sales'
ORDER BY OBJECT_NAME, ORDINAL_POSITION;

SELECT METRIC_NAME, EXPRESSION, FILTER_EXPR, METRIC_TYPE
FROM SEMANTIC_CATALOG.METRICS
WHERE MODEL_NAME = 'sales'
ORDER BY METRIC_NAME;

-- The metric/dimension pairs this model refuses to answer, and why. The demo
-- is multi-grain on purpose: order-grain freight cannot be attributed to a
-- product without fanning one order row out across its lines.
-- tools/verify_fanout_guardrails.py walks through the same guardrail live.
SELECT METRIC_NAME, DIMENSION_NAME, REASON_CODE, RELATIONSHIP_PATH
FROM SEMANTIC_CATALOG.METRIC_DIMENSION_MATRIX
WHERE MODEL_NAME = 'sales'
  AND NOT IS_VALID
ORDER BY METRIC_NAME, DIMENSION_NAME;
