CREATE SCHEMA IF NOT EXISTS MART;

DROP TABLE IF EXISTS MART.ORDER_LINES;
DROP TABLE IF EXISTS MART.ORDERS;
DROP TABLE IF EXISTS MART.CUSTOMERS;
DROP TABLE IF EXISTS MART.PRODUCTS;

CREATE TABLE MART.CUSTOMERS (
  CUSTOMER_ID      DECIMAL(18,0) PRIMARY KEY,
  CUSTOMER_NAME    VARCHAR(200),
  REGION           VARCHAR(100),
  SEGMENT          VARCHAR(40)
);

CREATE TABLE MART.PRODUCTS (
  PRODUCT_ID       DECIMAL(18,0) PRIMARY KEY,
  PRODUCT_NAME     VARCHAR(200),
  CATEGORY         VARCHAR(100)
);

-- FREIGHT_AMOUNT and SHIP_MODE live on the order header, not on the order
-- line. They are what make this demo multi-grain: an order-grain measure
-- cannot be attributed to a product without fanning one order row out across
-- its lines. See sql/examples/sales_model_seed.sql and the ORDER_HEADER object.
CREATE TABLE MART.ORDERS (
  ORDER_ID         DECIMAL(18,0) PRIMARY KEY,
  CUSTOMER_ID      DECIMAL(18,0) NOT NULL,
  ORDER_DATE       DATE NOT NULL,
  ORDER_STATUS     VARCHAR(32) NOT NULL,
  FREIGHT_AMOUNT   DECIMAL(18,2) NOT NULL,
  SHIP_MODE        VARCHAR(20) NOT NULL
);

CREATE TABLE MART.ORDER_LINES (
  ORDER_ID         DECIMAL(18,0) NOT NULL,
  LINE_ID          DECIMAL(18,0) NOT NULL,
  PRODUCT_ID       DECIMAL(18,0) NOT NULL,
  QUANTITY         DECIMAL(18,0) NOT NULL,
  NET_UNIT_PRICE   DECIMAL(18,2) NOT NULL,
  UNIT_COST        DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (ORDER_ID, LINE_ID)
);

INSERT INTO MART.CUSTOMERS VALUES (1, 'Acme Retail', 'North', 'Retail');
INSERT INTO MART.CUSTOMERS VALUES (2, 'Bright Market', 'South', 'Retail');
INSERT INTO MART.CUSTOMERS VALUES (3, 'Cobalt Stores', 'West', 'Retail');
INSERT INTO MART.CUSTOMERS VALUES (4, 'Delta Wholesale', 'North', 'Wholesale');

INSERT INTO MART.PRODUCTS VALUES (10, 'Road Bike', 'Bikes');
INSERT INTO MART.PRODUCTS VALUES (11, 'Helmet', 'Accessories');
INSERT INTO MART.PRODUCTS VALUES (12, 'Floor Pump', 'Accessories');
INSERT INTO MART.PRODUCTS VALUES (13, 'Touring Bike', 'Bikes');

INSERT INTO MART.ORDERS VALUES (1000, 1, DATE '2026-01-05', 'COMPLETE',  25.00, 'GROUND');
INSERT INTO MART.ORDERS VALUES (1001, 2, DATE '2026-01-20', 'COMPLETE',  12.50, 'GROUND');
INSERT INTO MART.ORDERS VALUES (1002, 3, DATE '2026-02-02', 'CANCELLED', 40.00, 'EXPRESS');
INSERT INTO MART.ORDERS VALUES (1003, 4, DATE '2026-02-12', 'COMPLETE',  18.75, 'EXPRESS');
INSERT INTO MART.ORDERS VALUES (1004, 1, DATE '2026-03-03', 'COMPLETE',   9.00, 'GROUND');

INSERT INTO MART.ORDER_LINES VALUES (1000, 1, 10, 1, 1200.00, 800.00);
INSERT INTO MART.ORDER_LINES VALUES (1000, 2, 11, 2, 80.00, 40.00);
INSERT INTO MART.ORDER_LINES VALUES (1001, 1, 12, 3, 45.00, 20.00);
INSERT INTO MART.ORDER_LINES VALUES (1002, 1, 13, 1, 1500.00, 1000.00);
INSERT INTO MART.ORDER_LINES VALUES (1003, 1, 10, 2, 1100.00, 780.00);
INSERT INTO MART.ORDER_LINES VALUES (1003, 2, 11, 1, 75.00, 40.00);
INSERT INTO MART.ORDER_LINES VALUES (1004, 1, 12, 1, 0.00, 0.00);
