SELECT *
FROM SEMANTIC_CATALOG.MODELS
WHERE MODEL_NAME = 'sales';

SELECT COLUMN_NAME, COLUMN_KIND, ORDINAL_POSITION, DISPLAY_NAME
FROM SEMANTIC_CATALOG.OBJECT_COLUMNS
WHERE MODEL_NAME = 'sales'
  AND OBJECT_NAME = 'SALES'
ORDER BY ORDINAL_POSITION;

SELECT METRIC_NAME, EXPRESSION, FILTER_EXPR, METRIC_TYPE
FROM SEMANTIC_CATALOG.METRICS
WHERE MODEL_NAME = 'sales'
ORDER BY METRIC_NAME;
