CREATE SCHEMA IF NOT EXISTS SYS_SEMANTIC;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_CATALOG;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_ADMIN;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_AGENT;

COMMENT ON SCHEMA SYS_SEMANTIC IS 'Internal catalog tables for Exasol Semantic Views.';
COMMENT ON SCHEMA SEMANTIC_CATALOG IS 'Readable semantic catalog views for models, entities, facts, metrics, validation, and materializations.';
COMMENT ON SCHEMA SEMANTIC_ADMIN IS 'Lua admin, compiler, validation, publish, preprocessor, and agent scripts for Exasol Semantic Views.';
COMMENT ON SCHEMA SEMANTIC_AGENT IS 'Agent-scoped semantic discovery views for models, objects, fields, valid combinations, glossary, and request history.';

CREATE TABLE IF NOT EXISTS SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY (
  ENTRY_NAME  VARCHAR(256),
  ENTRY_VALUE VARCHAR(2000000)
);

COMMENT ON TABLE SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY IS
  'MCP-visible discovery table for semantic catalog views. Generic MCP tools may list this table even when they omit views.';

DELETE FROM SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY;
INSERT INTO SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY VALUES
  ('PURPOSE', 'Readable semantic catalog views for Exasol Semantic Views.'),
  ('KEY_VIEWS', 'MODELS, SEMANTIC_OBJECTS, FACTS, METRICS, OBJECT_COLUMNS, VALIDATION_RESULTS, CURRENT_VALIDATION_ISSUES.'),
  ('MCP_GUIDANCE', 'If your MCP table-listing tool only returns this physical table, query the named SEMANTIC_CATALOG views directly with execute_exasol_query.'),
  ('METRIC_DEFINITIONS_QUERY', 'SELECT MODEL_NAME, OBJECT_NAME, METRIC_NAME, DISPLAY_NAME, DESCRIPTION FROM SEMANTIC_CATALOG.METRICS ORDER BY MODEL_NAME, OBJECT_NAME, METRIC_NAME'),
  ('VALIDATION_QUERY', 'SELECT MODEL_NAME, OBJECT_TYPE, OBJECT_NAME, RULE_CODE, MESSAGE FROM SEMANTIC_CATALOG.CURRENT_VALIDATION_ISSUES ORDER BY MODEL_NAME, OBJECT_TYPE, OBJECT_NAME');

CREATE TABLE IF NOT EXISTS SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY (
  ENTRY_NAME  VARCHAR(256),
  ENTRY_VALUE VARCHAR(2000000)
);

COMMENT ON TABLE SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY IS
  'MCP-visible discovery table for agent-facing semantic views. Generic MCP tools may list this table even when they omit views.';

DELETE FROM SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY;
INSERT INTO SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY VALUES
  ('PURPOSE', 'Agent-facing semantic discovery and request history views.'),
  ('KEY_VIEWS', 'MODELS_FOR_AGENT, OBJECTS_FOR_AGENT, FIELDS_FOR_AGENT, VALID_COMBINATIONS_FOR_AGENT, REQUEST_HISTORY_FOR_AGENT.'),
  ('MCP_GUIDANCE', 'If your MCP table-listing tool only returns this physical table, query the named SEMANTIC_AGENT views directly with execute_exasol_query.'),
  ('MODEL_DISCOVERY_QUERY', 'SELECT MODEL_NAME, PUBLISHED_SCHEMA, PUBLISHED_OBJECT_NAME, AGENT_READINESS FROM SEMANTIC_AGENT.OBJECTS_FOR_AGENT ORDER BY MODEL_NAME, OBJECT_NAME'),
  ('FIELD_DISCOVERY_QUERY', 'SELECT MODEL_NAME, OBJECT_NAME, FIELD_KIND, FIELD_NAME, DATA_TYPE, DESCRIPTION FROM SEMANTIC_AGENT.FIELDS_FOR_AGENT ORDER BY MODEL_NAME, OBJECT_NAME, FIELD_KIND, FIELD_NAME'),
  ('COMPATIBILITY_QUERY', 'SELECT MODEL_NAME, OBJECT_NAME, METRIC_NAME, DIMENSION_NAME, IS_VALID, REASON_CODE FROM SEMANTIC_AGENT.VALID_COMBINATIONS_FOR_AGENT ORDER BY MODEL_NAME, OBJECT_NAME, METRIC_NAME, DIMENSION_NAME');
