CREATE SCHEMA IF NOT EXISTS SYS_SEMANTIC;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_CATALOG;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_ADMIN;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_AGENT;

COMMENT ON SCHEMA SYS_SEMANTIC IS 'Internal catalog tables for Exasol Semantic Views.';
COMMENT ON SCHEMA SEMANTIC_CATALOG IS 'Readable semantic catalog views for models, entities, facts, metrics, validation, and materializations.';
COMMENT ON SCHEMA SEMANTIC_ADMIN IS 'Lua admin, compiler, validation, publish, preprocessor, and agent scripts for Exasol Semantic Views.';
COMMENT ON SCHEMA SEMANTIC_AGENT IS 'Agent-scoped semantic discovery views for models, objects, fields, valid combinations, glossary, and request history.';

CREATE TABLE IF NOT EXISTS SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY (
  ENTRY_NAME  VARCHAR(256),
  ENTRY_VALUE VARCHAR(2000000)
);

COMMENT ON TABLE SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY IS
  'MCP-visible discovery table for semantic catalog views. Generic MCP tools may list this table even when they omit views.';

DELETE FROM SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY;
INSERT INTO SEMANTIC_CATALOG.SEMANTIC_CATALOG_DISCOVERY VALUES
  ('PURPOSE', 'Readable semantic catalog views for Exasol Semantic Views.'),
  ('KEY_VIEWS', 'MODELS, SEMANTIC_OBJECTS, FACTS, METRICS, RELATIONSHIPS, RELATIONSHIP_KEY_MAPPINGS, OBJECT_COLUMNS, VALIDATION_RESULTS, CURRENT_VALIDATION_ISSUES, CATALOG_COLUMNS, CATALOG_RELATIONSHIPS.'),
  ('MCP_GUIDANCE', 'If your MCP table-listing tool only returns this physical table, query the named SEMANTIC_CATALOG views directly with execute_exasol_query.'),
  ('METRIC_DEFINITIONS_QUERY', 'SELECT MODEL_NAME, OBJECT_NAME, METRIC_NAME, DISPLAY_NAME, DESCRIPTION FROM SEMANTIC_CATALOG.METRIC_OVERVIEW ORDER BY MODEL_NAME, OBJECT_NAME, METRIC_NAME'),
  ('VALIDATION_QUERY', 'SELECT MODEL_NAME, OBJECT_TYPE, OBJECT_NAME, RULE_CODE, MESSAGE FROM SEMANTIC_CATALOG.CURRENT_VALIDATION_ISSUES ORDER BY MODEL_NAME, OBJECT_TYPE, OBJECT_NAME'),
  ('COLUMN_INTROSPECTION_QUERY', 'SELECT ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE FROM SEMANTIC_CATALOG.CATALOG_COLUMNS WHERE SURFACE_NAME = ''CURRENT_VALIDATION_ISSUES'' ORDER BY ORDINAL_POSITION'),
  ('JOIN_INTROSPECTION_QUERY', 'SELECT RELATIONSHIP_KIND, CHILD_COLUMN, PARENT_SURFACE, JOIN_TEMPLATE FROM SEMANTIC_CATALOG.CATALOG_RELATIONSHIPS WHERE CHILD_SURFACE = ''METRIC_INPUTS'' ORDER BY RELATIONSHIP_KIND, CHILD_COLUMN'),
  ('JOIN_INTROSPECTION_GUIDANCE', 'Do not guess how two surfaces join. CATALOG_RELATIONSHIPS carries every edge in the installation: declared foreign keys on the SYS_SEMANTIC tables, the polymorphic references SQL cannot declare (join those on the discriminator column as well, or rows of different object kinds sharing an id will silently mix), and the ID columns the catalog and agent views expose. JOIN_TEMPLATE is the ON clause, ready to paste.');

CREATE TABLE IF NOT EXISTS SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY (
  ENTRY_NAME  VARCHAR(256),
  ENTRY_VALUE VARCHAR(2000000)
);

COMMENT ON TABLE SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY IS
  'MCP-visible discovery table for agent-facing semantic views. Generic MCP tools may list this table even when they omit views.';

DELETE FROM SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY;
INSERT INTO SEMANTIC_AGENT.SEMANTIC_AGENT_DISCOVERY VALUES
  ('PURPOSE', 'Agent-facing semantic discovery and request history views.'),
  ('KEY_VIEWS', 'MODELS_FOR_AGENT, OBJECTS_FOR_AGENT, FIELDS_FOR_AGENT, VALID_COMBINATIONS_FOR_AGENT, REQUEST_HISTORY_FOR_AGENT, COMPILE_RESULT_SCHEMA_FOR_AGENT, FUSION_FOR_AGENT, DEPLOYMENT_IDENTITY_FOR_AGENT.'),
  ('MCP_GUIDANCE', 'If your MCP table-listing tool only returns this physical table, query the named SEMANTIC_AGENT views directly with execute_exasol_query.'),
  ('MODEL_DISCOVERY_QUERY', 'SELECT MODEL_NAME, PUBLISHED_SCHEMA, PUBLISHED_OBJECT_NAME, AGENT_READINESS FROM SEMANTIC_AGENT.OBJECTS_FOR_AGENT ORDER BY MODEL_NAME, OBJECT_NAME'),
  ('FIELD_DISCOVERY_QUERY', 'SELECT MODEL_NAME, OBJECT_NAME, FIELD_KIND, FIELD_NAME, DATA_TYPE, DESCRIPTION FROM SEMANTIC_AGENT.FIELDS_FOR_AGENT ORDER BY MODEL_NAME, OBJECT_NAME, FIELD_KIND, FIELD_NAME'),
  ('COMPATIBILITY_QUERY', 'SELECT MODEL_NAME, OBJECT_NAME, METRIC_NAME, DIMENSION_NAME, IS_VALID, REASON_CODE FROM SEMANTIC_AGENT.VALID_COMBINATIONS_FOR_AGENT ORDER BY MODEL_NAME, OBJECT_NAME, METRIC_NAME, DIMENSION_NAME'),
  ('EXPRESSION_FUNCTION_QUERY', 'SELECT FUNCTION_NAME, FUNCTION_CATEGORY FROM SEMANTIC_AGENT.EXPRESSION_FUNCTIONS_FOR_AGENT ORDER BY FUNCTION_NAME'),
  ('COMPILE_RESULT_QUERY', 'SELECT ORDINAL_POSITION, COLUMN_NAME, NULL_WHEN FROM SEMANTIC_AGENT.COMPILE_RESULT_SCHEMA_FOR_AGENT WHERE SCRIPT_NAME = ''COMPILE_SQL'' ORDER BY ORDINAL_POSITION'),
  ('FUSION_QUERY', 'SELECT ENTITY_NAME, FUSION_ASPECT, REPRESENTATION_NAME, ATTRIBUTE_NAME, STRATEGY FROM SEMANTIC_AGENT.FUSION_FOR_AGENT ORDER BY ENTITY_NAME, FUSION_ASPECT'),
  ('DEPLOYMENT_IDENTITY_QUERY', 'SELECT DATABASE_NAME, PRODUCT_VERSION, RUNTIME_CHECKSUM, MODEL_COUNT FROM SEMANTIC_AGENT.DEPLOYMENT_IDENTITY_FOR_AGENT'),
  ('JOIN_INTROSPECTION_QUERY', 'SELECT RELATIONSHIP_KIND, CHILD_SURFACE, CHILD_COLUMN, PARENT_SURFACE, JOIN_TEMPLATE FROM SEMANTIC_CATALOG.CATALOG_RELATIONSHIPS ORDER BY CHILD_SURFACE, CHILD_COLUMN'),
  ('JOIN_INTROSPECTION_GUIDANCE', 'The SEMANTIC_AGENT views are pre-joined and answer most questions without a join. When you do need to connect two surfaces -- or need to read the SYS_SEMANTIC tables underneath -- SEMANTIC_CATALOG.CATALOG_RELATIONSHIPS has every edge and a ready-to-paste JOIN_TEMPLATE. Views carry no SQL constraints, so EXA_ALL_CONSTRAINT_COLUMNS alone shows only part of the graph.'),
  ('DEPLOYMENT_IDENTITY_GUIDANCE', 'A client pinned to a static host:port can reach a different deployment than intended -- Exasol Personal reassigns ports on restart. Assert DATABASE_NAME plus RUNTIME_CHECKSUM before trusting any answer from this catalog.');
