CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODELS (
  MODEL_ID             DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_NAME           VARCHAR(256) NOT NULL,
  PUBLISHED_SCHEMA     VARCHAR(256),
  DESCRIPTION          VARCHAR(2000000),
  OWNER_ROLE           VARCHAR(256),
  STATUS               VARCHAR(32) DEFAULT 'DRAFT' NOT NULL,
  ACTIVE_VERSION_ID    DECIMAL(18,0),
  PREPROCESSOR_SCHEMA  VARCHAR(256),
  PREPROCESSOR_SCRIPT  VARCHAR(256),
  SURFACE_TYPE         VARCHAR(32) DEFAULT 'VIEW_PREPROCESSOR',
  GOVERNANCE_MODE      VARCHAR(16) DEFAULT 'OPEN' NOT NULL,
  ALLOW_DERIVED_COMPOSITION BOOLEAN DEFAULT FALSE NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_VERSIONS (
  VERSION_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID         DECIMAL(18,0) NOT NULL,
  VERSION_NUMBER   DECIMAL(18,0) NOT NULL,
  VERSION_LABEL    VARCHAR(256),
  STATUS           VARCHAR(32) DEFAULT 'DRAFT' NOT NULL,
  CHANGE_SUMMARY   VARCHAR(2000000),
  CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY       VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.ENTITIES (
  ENTITY_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_NAME        VARCHAR(256) NOT NULL,
  SOURCE_SCHEMA      VARCHAR(256) NOT NULL,
  SOURCE_OBJECT      VARCHAR(256) NOT NULL,
  SOURCE_ALIAS       VARCHAR(128) NOT NULL,
  PRIMARY_KEY_EXPR   VARCHAR(2000000),
  GRAIN_DESCRIPTION  VARCHAR(2000000),
  DESCRIPTION        VARCHAR(2000000),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.ENTITY_REPRESENTATIONS (
  REPRESENTATION_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  ENTITY_ID            DECIMAL(18,0) NOT NULL,
  REPRESENTATION_NAME  VARCHAR(256) NOT NULL,
  SOURCE_KIND          VARCHAR(64) DEFAULT 'RELATION' NOT NULL,
  SOURCE_SCHEMA        VARCHAR(256) NOT NULL,
  SOURCE_OBJECT        VARCHAR(256) NOT NULL,
  SOURCE_ALIAS         VARCHAR(128) NOT NULL,
  REPRESENTATION_ROLE  VARCHAR(64) DEFAULT 'ALTERNATE' NOT NULL,
  PRIORITY             DECIMAL(18,0) DEFAULT 1 NOT NULL,
  FRESHNESS_POLICY     VARCHAR(2000000),
  COVERAGE_PREDICATE   VARCHAR(2000000),
  VALID_FROM           TIMESTAMP,
  VALID_TO             TIMESTAMP,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

-- F0 compatibility migration: each pre-representation entity receives one
-- physical source binding with no change to its existing source semantics.
INSERT INTO SYS_SEMANTIC.ENTITY_REPRESENTATIONS (
  MODEL_ID, VERSION_ID, ENTITY_ID, REPRESENTATION_NAME, SOURCE_KIND,
  SOURCE_SCHEMA, SOURCE_OBJECT, SOURCE_ALIAS, REPRESENTATION_ROLE, PRIORITY,
  STATUS
)
SELECT
  e.MODEL_ID, e.VERSION_ID, e.ENTITY_ID, 'primary', 'RELATION',
  e.SOURCE_SCHEMA, e.SOURCE_OBJECT, e.SOURCE_ALIAS, 'PRIMARY', 1, e.STATUS
FROM SYS_SEMANTIC.ENTITIES e
WHERE NOT EXISTS (
  SELECT 1
  FROM SYS_SEMANTIC.ENTITY_REPRESENTATIONS er
  WHERE er.ENTITY_ID = e.ENTITY_ID
    AND er.REPRESENTATION_ROLE = 'PRIMARY'
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.UNIQUE_KEYS (
  UNIQUE_KEY_ID      DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_ID          DECIMAL(18,0) NOT NULL,
  KEY_NAME           VARCHAR(256) NOT NULL,
  KEY_KIND           VARCHAR(64) DEFAULT 'UNIQUE' NOT NULL,
  DESCRIPTION        VARCHAR(2000000),
  SOURCE_FORMAT      VARCHAR(64) DEFAULT 'OSI' NOT NULL,
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY         VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT         TIMESTAMP,
  UPDATED_BY         VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.UNIQUE_KEY_COLUMNS (
  UNIQUE_KEY_ID      DECIMAL(18,0) NOT NULL,
  ORDINAL_POSITION   DECIMAL(18,0) NOT NULL,
  COLUMN_NAME        VARCHAR(256),
  EXPRESSION         VARCHAR(2000000),
  PRIMARY KEY (UNIQUE_KEY_ID, ORDINAL_POSITION)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SEMANTIC_OBJECTS (
  OBJECT_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  OBJECT_NAME        VARCHAR(256) NOT NULL,
  ROOT_ENTITY_ID     DECIMAL(18,0),
  DESCRIPTION        VARCHAR(2000000),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

-- Provenance of the installed runtime. Everything else in this catalog
-- describes the semantic model; this describes the product build serving it.
-- The runtime lives inside the database, so "which build is this deployment
-- running?" has to be answerable in SQL: comparing catalog schemas by hand to
-- discover that one deployment is simply older is not a diagnosis path.
--
-- One row per tools/install.py run; IF NOT EXISTS keeps the history across
-- re-installs that do not --reset. RUNTIME_CHECKSUM covers the install SQL
-- files as executed, so it distinguishes builds even when git provenance is
-- unavailable (tarball, vendored copy, uncommitted edits).
CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.PRODUCT_INSTALLATIONS (
  INSTALLATION_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  PRODUCT_VERSION    VARCHAR(64) NOT NULL,
  RELEASE_STATE      VARCHAR(32) NOT NULL,
  GIT_COMMIT         VARCHAR(64),
  GIT_STATE          VARCHAR(16),
  RUNTIME_CHECKSUM   VARCHAR(64) NOT NULL,
  INSTALLED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INSTALLED_BY       VARCHAR(256) DEFAULT CURRENT_USER NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.RELATIONSHIPS (
  RELATIONSHIP_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  RELATIONSHIP_NAME  VARCHAR(256) NOT NULL,
  FROM_ENTITY_ID     DECIMAL(18,0) NOT NULL,
  TO_ENTITY_ID       DECIMAL(18,0) NOT NULL,
  JOIN_CONDITION     VARCHAR(2000000) NOT NULL,
  RELATIONSHIP_CARDINALITY VARCHAR(64) NOT NULL,
  JOIN_TYPE          VARCHAR(32) DEFAULT 'LEFT' NOT NULL,
  IS_REQUIRED        BOOLEAN DEFAULT FALSE,
  FANOUT_POLICY      VARCHAR(64),
  PATH_PRIORITY      DECIMAL(18,0) DEFAULT 100,
  DESCRIPTION        VARCHAR(2000000),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.RELATIONSHIP_KEY_MAPPINGS (
  RELATIONSHIP_ID    DECIMAL(18,0) NOT NULL,
  ORDINAL_POSITION   DECIMAL(18,0) NOT NULL,
  FROM_COLUMN_NAME   VARCHAR(256),
  FROM_EXPRESSION    VARCHAR(2000000),
  TO_COLUMN_NAME     VARCHAR(256),
  TO_EXPRESSION      VARCHAR(2000000),
  PRIMARY KEY (RELATIONSHIP_ID, ORDINAL_POSITION)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.DIMENSIONS (
  DIMENSION_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_ID          DECIMAL(18,0) NOT NULL,
  DIMENSION_NAME     VARCHAR(256) NOT NULL,
  EXPRESSION         VARCHAR(2000000) NOT NULL,
  DATA_TYPE          VARCHAR(128) NOT NULL,
  DISPLAY_NAME       VARCHAR(512),
  DESCRIPTION        VARCHAR(2000000),
  FORMAT_HINT        VARCHAR(512),
  UNIT_HINT          VARCHAR(256),
  SENSITIVITY_LABEL  VARCHAR(256),
  DISPLAY_POLICY     VARCHAR(512),
  IS_HIDDEN          BOOLEAN DEFAULT FALSE,
  IS_CERTIFIED       BOOLEAN DEFAULT FALSE,
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.FACTS (
  FACT_ID            DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_ID          DECIMAL(18,0) NOT NULL,
  FACT_NAME          VARCHAR(256) NOT NULL,
  EXPRESSION         VARCHAR(2000000) NOT NULL,
  DATA_TYPE          VARCHAR(128) NOT NULL,
  ADDITIVE_POLICY    VARCHAR(64) DEFAULT 'ADDITIVE' NOT NULL,
  DISPLAY_NAME       VARCHAR(512),
  DESCRIPTION        VARCHAR(2000000),
  FORMAT_HINT        VARCHAR(512),
  UNIT_HINT          VARCHAR(256),
  SENSITIVITY_LABEL  VARCHAR(256),
  DISPLAY_POLICY     VARCHAR(512),
  IS_PRIVATE         BOOLEAN DEFAULT FALSE,
  IS_CERTIFIED       BOOLEAN DEFAULT FALSE,
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.ATTRIBUTE_BINDINGS (
  ATTRIBUTE_BINDING_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  ENTITY_ID            DECIMAL(18,0) NOT NULL,
  ATTRIBUTE_TYPE       VARCHAR(32) NOT NULL,
  ATTRIBUTE_ID         DECIMAL(18,0) NOT NULL,
  REPRESENTATION_ID    DECIMAL(18,0) NOT NULL,
  SOURCE_EXPRESSION    VARCHAR(2000000) NOT NULL,
  BINDING_ROLE         VARCHAR(32) DEFAULT 'FALLBACK' NOT NULL,
  BINDING_PRIORITY     DECIMAL(18,0) DEFAULT 1 NOT NULL,
  IS_DEFAULT           BOOLEAN DEFAULT FALSE NOT NULL,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.REPRESENTATION_AUTHORITIES (
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  ENTITY_ID            DECIMAL(18,0) NOT NULL,
  REPRESENTATION_ID    DECIMAL(18,0) NOT NULL,
  AUTHORITY_ROLE       VARCHAR(32) DEFAULT 'PREFER' NOT NULL,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256),
  PRIMARY KEY (MODEL_ID, VERSION_ID, REPRESENTATION_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES (
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  ENTITY_ID            DECIMAL(18,0) NOT NULL,
  ATTRIBUTE_TYPE       VARCHAR(32) NOT NULL,
  ATTRIBUTE_ID         DECIMAL(18,0) NOT NULL,
  FUSION_STRATEGY      VARCHAR(32) DEFAULT 'PREFER' NOT NULL,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256),
  PRIMARY KEY (MODEL_ID, VERSION_ID, ATTRIBUTE_TYPE, ATTRIBUTE_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SEMANTIC_IDENTITIES (
  IDENTITY_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  ENTITY_ID            DECIMAL(18,0) NOT NULL,
  IDENTITY_NAME        VARCHAR(256) NOT NULL,
  IDENTITY_KIND        VARCHAR(32) DEFAULT 'GLOBAL' NOT NULL,
  DATA_TYPE            VARCHAR(128) NOT NULL,
  DESCRIPTION          VARCHAR(2000000),
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.IDENTITY_BINDINGS (
  IDENTITY_BINDING_ID  DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  ENTITY_ID            DECIMAL(18,0) NOT NULL,
  IDENTITY_ID          DECIMAL(18,0) NOT NULL,
  REPRESENTATION_ID    DECIMAL(18,0) NOT NULL,
  SOURCE_EXPRESSION    VARCHAR(2000000) NOT NULL,
  BINDING_KIND         VARCHAR(32) DEFAULT 'DIRECT' NOT NULL,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS (
  IDENTITY_MAPPING_ID  DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  IDENTITY_BINDING_ID  DECIMAL(18,0) NOT NULL,
  SOURCE_SCHEMA        VARCHAR(256) NOT NULL,
  SOURCE_OBJECT        VARCHAR(256) NOT NULL,
  SOURCE_LOCAL_COLUMN  VARCHAR(256) NOT NULL,
  SEMANTIC_KEY_COLUMN  VARCHAR(256) NOT NULL,
  CERTIFICATION_STATUS VARCHAR(32) DEFAULT 'CERTIFIED' NOT NULL,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

-- F2 compatibility migration: legacy expressions remain authoritative and
-- become the preferred binding on each entity's PRIMARY representation.
INSERT INTO SYS_SEMANTIC.ATTRIBUTE_BINDINGS (
  MODEL_ID, VERSION_ID, ENTITY_ID, ATTRIBUTE_TYPE, ATTRIBUTE_ID,
  REPRESENTATION_ID, SOURCE_EXPRESSION, BINDING_ROLE, BINDING_PRIORITY, IS_DEFAULT, STATUS
)
SELECT d.MODEL_ID, d.VERSION_ID, d.ENTITY_ID, 'DIMENSION', d.DIMENSION_ID,
       er.REPRESENTATION_ID, d.EXPRESSION, 'PREFER', 1, TRUE, d.STATUS
FROM SYS_SEMANTIC.DIMENSIONS d
JOIN SYS_SEMANTIC.ENTITY_REPRESENTATIONS er
  ON er.ENTITY_ID = d.ENTITY_ID
 AND er.MODEL_ID = d.MODEL_ID
 AND er.VERSION_ID = d.VERSION_ID
 AND er.REPRESENTATION_ROLE = 'PRIMARY'
 AND er.STATUS = 'ACTIVE'
WHERE NOT EXISTS (
  SELECT 1 FROM SYS_SEMANTIC.ATTRIBUTE_BINDINGS ab
  WHERE ab.ATTRIBUTE_TYPE = 'DIMENSION' AND ab.ATTRIBUTE_ID = d.DIMENSION_ID
);

INSERT INTO SYS_SEMANTIC.ATTRIBUTE_BINDINGS (
  MODEL_ID, VERSION_ID, ENTITY_ID, ATTRIBUTE_TYPE, ATTRIBUTE_ID,
  REPRESENTATION_ID, SOURCE_EXPRESSION, BINDING_ROLE, BINDING_PRIORITY, IS_DEFAULT, STATUS
)
SELECT f.MODEL_ID, f.VERSION_ID, f.ENTITY_ID, 'FACT', f.FACT_ID,
       er.REPRESENTATION_ID, f.EXPRESSION, 'PREFER', 1, TRUE, f.STATUS
FROM SYS_SEMANTIC.FACTS f
JOIN SYS_SEMANTIC.ENTITY_REPRESENTATIONS er
  ON er.ENTITY_ID = f.ENTITY_ID
 AND er.MODEL_ID = f.MODEL_ID
 AND er.VERSION_ID = f.VERSION_ID
 AND er.REPRESENTATION_ROLE = 'PRIMARY'
 AND er.STATUS = 'ACTIVE'
WHERE NOT EXISTS (
  SELECT 1 FROM SYS_SEMANTIC.ATTRIBUTE_BINDINGS ab
  WHERE ab.ATTRIBUTE_TYPE = 'FACT' AND ab.ATTRIBUTE_ID = f.FACT_ID
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRICS (
  METRIC_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  METRIC_NAME        VARCHAR(256) NOT NULL,
  EXPRESSION         VARCHAR(2000000) NOT NULL,
  FILTER_EXPR        VARCHAR(2000000),
  METRIC_TYPE        VARCHAR(64) NOT NULL,
  BASE_ENTITY_ID     DECIMAL(18,0),
  DATA_TYPE          VARCHAR(128) NOT NULL,
  DISPLAY_NAME       VARCHAR(512),
  DESCRIPTION        VARCHAR(2000000),
  FORMAT_HINT        VARCHAR(512),
  UNIT_HINT          VARCHAR(256),
  SENSITIVITY_LABEL  VARCHAR(256),
  DISPLAY_POLICY     VARCHAR(512),
  IS_PRIVATE         BOOLEAN DEFAULT FALSE,
  IS_CERTIFIED       BOOLEAN DEFAULT FALSE,
  OWNER_ROLE         VARCHAR(256),
  METRIC_KIND        VARCHAR(64),
  AGGREGATION_FUNCTION VARCHAR(64),
  MEASURE_EXPR       VARCHAR(2000000),
  SEMANTIC_FILTER_EXPR VARCHAR(2000000),
  SQL_FILTER_EXPR    VARCHAR(2000000),
  DISTINCT_KEY_EXPR  VARCHAR(2000000),
  NON_ADDITIVE_DIMENSION_ID DECIMAL(18,0),
  WINDOW_SPEC_JSON   VARCHAR(2000000),
  TYPE_PARAMS_JSON   VARCHAR(2000000),
  DEFINITION_SOURCE_ID DECIMAL(18,0),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

COMMENT ON TABLE SYS_SEMANTIC.METRICS (
  METRIC_TYPE IS 'Additive storage policy used by the compiler (SIMPLE, FILTERED, RATIO, DERIVED, WINDOW). Determines join and aggregation strategy.',
  METRIC_KIND IS 'Semantic classification for agents and discovery (SIMPLE, FILTERED, RATIO, DERIVED). Use this column for display and filtering.'
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.OBJECT_COLUMNS (
  OBJECT_ID          DECIMAL(18,0) NOT NULL,
  COLUMN_KIND        VARCHAR(32) NOT NULL,
  OBJECT_REF_ID      DECIMAL(18,0) NOT NULL,
  COLUMN_NAME        VARCHAR(256) NOT NULL,
  ORDINAL_POSITION   DECIMAL(18,0) NOT NULL,
  IS_VISIBLE         BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (OBJECT_ID, COLUMN_KIND, OBJECT_REF_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_DEPENDENCIES (
  METRIC_ID              DECIMAL(18,0) NOT NULL,
  DEPENDS_ON_OBJECT_TYPE VARCHAR(64) NOT NULL,
  DEPENDS_ON_OBJECT_ID   DECIMAL(18,0) NOT NULL,
  DEPENDENCY_KIND        VARCHAR(64) DEFAULT 'DIRECT' NOT NULL,
  PRIMARY KEY (METRIC_ID, DEPENDS_ON_OBJECT_TYPE, DEPENDS_ON_OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES (
  DEFINITION_SOURCE_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0),
  VERSION_ID           DECIMAL(18,0),
  SOURCE_KIND          VARCHAR(64) NOT NULL,
  SOURCE_NAME          VARCHAR(512),
  DEFINITION_SQL       VARCHAR(2000000) NOT NULL,
  NORMALIZED_JSON      VARCHAR(2000000),
  DEFINITION_HASH      VARCHAR(128),
  APPLY_STATUS         VARCHAR(64) DEFAULT 'APPLIED' NOT NULL,
  VALIDATION_RUN_ID    DECIMAL(18,0),
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_INPUTS (
  METRIC_ID            DECIMAL(18,0) NOT NULL,
  INPUT_ROLE           VARCHAR(64) NOT NULL,
  INPUT_OBJECT_TYPE    VARCHAR(64) NOT NULL,
  INPUT_OBJECT_ID      DECIMAL(18,0),
  EXPRESSION_ALIAS     VARCHAR(256),
  OFFSET_WINDOW        VARCHAR(512),
  FILTER_EXPR          VARCHAR(2000000),
  ORDINAL_POSITION     DECIMAL(18,0) NOT NULL,
  PRIMARY KEY (METRIC_ID, INPUT_ROLE, ORDINAL_POSITION)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_FILTERS (
  METRIC_ID            DECIMAL(18,0) NOT NULL,
  FILTER_KIND          VARCHAR(64) NOT NULL,
  FILTER_EXPR          VARCHAR(2000000) NOT NULL,
  RESOLVED_SQL_EXPR    VARCHAR(2000000),
  REQUIRED_DIMENSION_ID DECIMAL(18,0),
  REQUIRED_ENTITY_ID   DECIMAL(18,0),
  ORDINAL_POSITION     DECIMAL(18,0) DEFAULT 1 NOT NULL,
  PRIMARY KEY (METRIC_ID, FILTER_KIND, ORDINAL_POSITION)
);

-- CALCULATION_GROUPS and CALCULATION_ITEMS were declared for a calculation-item
-- feature that was never built: nothing wrote them, nothing read them, and
-- compilation did not consult them. Two nouns and two foreign keys in a catalog
-- a user browses, standing for behaviour that does not exist. Dropped rather
-- than kept as a promise; if the feature arrives it can declare its own tables.
-- DROP is idempotent and the tables were always empty, so an upgrade loses
-- nothing.
DROP TABLE IF EXISTS SYS_SEMANTIC.CALCULATION_ITEMS CASCADE;
DROP TABLE IF EXISTS SYS_SEMANTIC.CALCULATION_GROUPS CASCADE;

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SYNONYMS (
  SYNONYM_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID      DECIMAL(18,0) NOT NULL,
  VERSION_ID    DECIMAL(18,0) NOT NULL,
  OBJECT_TYPE   VARCHAR(64) NOT NULL,
  OBJECT_ID     DECIMAL(18,0) NOT NULL,
  SYNONYM       VARCHAR(512) NOT NULL,
  SYNONYM_SOURCE VARCHAR(64) DEFAULT 'MANUAL'
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.CUSTOM_EXTENSIONS (
  CUSTOM_EXTENSION_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID            DECIMAL(18,0) NOT NULL,
  VERSION_ID          DECIMAL(18,0) NOT NULL,
  SCOPE_TYPE          VARCHAR(64) NOT NULL,
  SCOPE_ID            DECIMAL(18,0) NOT NULL,
  VENDOR_NAME         VARCHAR(256) NOT NULL,
  EXTENSION_NAME      VARCHAR(256) DEFAULT 'default' NOT NULL,
  SOURCE_FORMAT       VARCHAR(64) DEFAULT 'OSI' NOT NULL,
  DATA_JSON           VARCHAR(2000000) NOT NULL,
  CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY          VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT          TIMESTAMP,
  UPDATED_BY          VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_INSTRUCTIONS (
  INSTRUCTION_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  SCOPE_TYPE           VARCHAR(64) NOT NULL,
  SCOPE_ID             DECIMAL(18,0),
  INSTRUCTION_KIND     VARCHAR(64) NOT NULL,
  INSTRUCTION_TEXT     VARCHAR(2000000) NOT NULL,
  APPLIES_TO_ROLE      VARCHAR(256),
  PRIORITY             DECIMAL(18,0) DEFAULT 100,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.VERIFIED_QUERIES (
  VERIFIED_QUERY_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID                DECIMAL(18,0) NOT NULL,
  VERSION_ID              DECIMAL(18,0) NOT NULL,
  OBJECT_ID               DECIMAL(18,0),
  QUERY_NAME              VARCHAR(512) NOT NULL,
  NATURAL_LANGUAGE_TEXT   VARCHAR(2000000) NOT NULL,
  REQUEST_JSON            VARCHAR(2000000) NOT NULL,
  GENERATED_SQL           VARCHAR(2000000),
  EXPECTED_RESULT_SHAPE   VARCHAR(2000000),
  IS_ONBOARDING_EXAMPLE   BOOLEAN DEFAULT FALSE,
  VERIFIED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERIFIED_BY             VARCHAR(256) DEFAULT CURRENT_USER,
  STATUS                  VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_REQUEST_LOG (
  AGENT_REQUEST_ID      DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID              DECIMAL(18,0),
  VERSION_ID            DECIMAL(18,0),
  USER_NAME             VARCHAR(256) DEFAULT CURRENT_USER,
  CLIENT_NAME           VARCHAR(512),
  PURPOSE               VARCHAR(512),
  NATURAL_LANGUAGE_TEXT VARCHAR(2000000),
  REQUEST_JSON          VARCHAR(2000000),
  GENERATED_SQL         VARCHAR(2000000),
  PLAN_JSON             VARCHAR(2000000),
  STATUS                VARCHAR(64),
  ERROR_CODE            VARCHAR(128),
  ERROR_MESSAGE         VARCHAR(2000000),
  REQUESTED_METRICS     VARCHAR(2000000),
  REQUESTED_DIMENSIONS  VARCHAR(2000000),
  CACHE_HIT             BOOLEAN DEFAULT FALSE,
  STARTED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FINISHED_AT           TIMESTAMP,
  RUNTIME_MS            DECIMAL(18,0)
);

-- Server-side compile cache (BUG-D-002). The compiler is deterministic per
-- (model_version_id, normalized request), so a successful compile is reused
-- until PUBLISH_MODEL invalidates the entry. CACHE_KEY is an FNV-1a hex hash
-- computed in Lua over the canonical parsed request (sorted top-level keys,
-- client/purpose stripped). Entries are written best-effort: a transient
-- collision on insert (PK conflict from a concurrent identical compile) is
-- swallowed and the caller still sees the compile result.
CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.COMPILE_CACHE (
  MODEL_VERSION_ID  DECIMAL(18,0) NOT NULL,
  CACHE_KEY         VARCHAR(64)   NOT NULL,
  GENERATED_SQL     VARCHAR(2000000),
  PLAN_JSON         VARCHAR(2000000),
  VALIDATION_RUN_ID DECIMAL(18,0),
  CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_HIT_AT       TIMESTAMP,
  HIT_COUNT         DECIMAL(18,0) DEFAULT 0,
  PRIMARY KEY (MODEL_VERSION_ID, CACHE_KEY)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_FEEDBACK (
  FEEDBACK_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  AGENT_REQUEST_ID     DECIMAL(18,0),
  QUERY_LOG_ID         DECIMAL(18,0),
  FEEDBACK_KIND        VARCHAR(64) NOT NULL,
  VERDICT              VARCHAR(64) NOT NULL,
  COMMENT_TEXT         VARCHAR(2000000),
  PROPOSED_CHANGE_JSON VARCHAR(2000000),
  REVIEW_STATUS        VARCHAR(64) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS (
  SUGGESTION_ID        DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0),
  VERSION_ID           DECIMAL(18,0),
  AGENT_REQUEST_ID     DECIMAL(18,0),
  QUERY_LOG_ID         DECIMAL(18,0),
  FEEDBACK_ID          DECIMAL(18,0),
  SUGGESTION_KIND      VARCHAR(64) NOT NULL,
  OBJECT_TYPE          VARCHAR(64),
  OBJECT_ID            DECIMAL(18,0),
  PROPOSED_CHANGE_JSON VARCHAR(2000000) NOT NULL,
  RATIONALE            VARCHAR(2000000),
  REVIEW_STATUS        VARCHAR(64) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  REVIEWED_AT          TIMESTAMP,
  REVIEWED_BY          VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_EVOLUTION_REVIEWS (
  REVIEW_ID      DECIMAL(18,0) IDENTITY PRIMARY KEY,
  SUGGESTION_ID  DECIMAL(18,0) NOT NULL,
  DECISION       VARCHAR(64) NOT NULL,
  REVIEW_NOTE    VARCHAR(2000000) NOT NULL,
  REVIEWED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  REVIEWED_BY    VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_EVOLUTION_TARGETS (
  SUGGESTION_ID  DECIMAL(18,0) PRIMARY KEY,
  OBJECT_NAME    VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MATERIALIZATIONS (
  MATERIALIZATION_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID              DECIMAL(18,0) NOT NULL,
  VERSION_ID            DECIMAL(18,0) NOT NULL,
  MATERIALIZATION_NAME  VARCHAR(256) NOT NULL,
  PHYSICAL_SCHEMA       VARCHAR(256) NOT NULL,
  PHYSICAL_OBJECT       VARCHAR(256) NOT NULL,
  MATERIALIZATION_TYPE  VARCHAR(64) NOT NULL,
  FRESHNESS_POLICY      VARCHAR(512),
  STATUS                VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

-- One trust class for every physical relation the planner may emit into SQL.
--
-- Representations and materializations used to be governed by different rules,
-- which is how a materialization built over the raw mart could silently void a
-- representation's row-level security: each was checked, neither was compared to
-- the other. They are the same question -- is this relation inside the set the
-- layer vouches for? -- so they get one derivation and one table.
--
-- Derived by VALIDATE_MODEL, never declared: TRUST_CLASS and BASE_RELATIONS are
-- resolved from SYS.EXA_ALL_DEPENDENCIES. RELATION_ID is a discriminated
-- reference -- a REPRESENTATION_ID or a MATERIALIZATION_ID according to
-- RELATION_KIND -- so it carries no foreign key; always join on the
-- discriminator too.
CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SOURCE_TRUST (
  TRUST_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID          DECIMAL(18,0) NOT NULL,
  VERSION_ID        DECIMAL(18,0) NOT NULL,
  RELATION_KIND     VARCHAR(32) NOT NULL,
  RELATION_ID       DECIMAL(18,0) NOT NULL,
  RELATION_NAME     VARCHAR(256),
  PHYSICAL_SCHEMA   VARCHAR(256) NOT NULL,
  PHYSICAL_OBJECT   VARCHAR(256) NOT NULL,
  TRUST_CLASS       VARCHAR(32) NOT NULL,
  BASE_RELATIONS    VARCHAR(2000000),
  DERIVED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SYS_SEMANTIC.SOURCE_TRUST (
  RELATION_KIND IS 'Which kind of physical relation this row classifies: REPRESENTATION or MATERIALIZATION.',
  RELATION_ID IS 'Discriminated reference -- a REPRESENTATION_ID or a MATERIALIZATION_ID according to RELATION_KIND. Join on the discriminator too, or rows of different kinds sharing an id will mix.',
  TRUST_CLASS IS 'GOVERNED (a view stands between the caller and the base tables), RAW (the relation is a base table), DIVERGENT (a materialization whose base relations differ from the representations it can replace, so it does not carry their policy), or UNKNOWN (dependencies could not be resolved).',
  BASE_RELATIONS IS 'The resolved transitive base tables, sorted and comma-separated. What DIVERGENT is decided by.'
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MATERIALIZATION_COLUMNS (
  MATERIALIZATION_ID DECIMAL(18,0) NOT NULL,
  OBJECT_TYPE        VARCHAR(64) NOT NULL,
  OBJECT_ID          DECIMAL(18,0) NOT NULL,
  PHYSICAL_COLUMN    VARCHAR(256) NOT NULL,
  ROLLUP_POLICY      VARCHAR(64),
  PRIMARY KEY (MATERIALIZATION_ID, OBJECT_TYPE, OBJECT_ID)
);

-- OBJECT_PRIVILEGES was an object-level ACL that nothing could populate: eight
-- of its ten columns had no writer anywhere in the product, and no GRANT script
-- reached it. OBJECTS_FOR_AGENT did read it, which made it look live -- but the
-- filter was "deny only if a grant exists", and since no grant could exist it
-- always evaluated to allow. Two dozen lines of SQL enforcing nothing, and a
-- governance promise in a catalog an admin browses.
--
-- Access control that does work is Exasol's own: PUBLISH_MODEL grants on the
-- published schema and MODEL_ROLE_GRANTS records it. Dropped rather than kept
-- as a promise, as CALCULATION_GROUPS was; if object-level privileges arrive
-- they can declare their own table alongside the scripts that write it.
DROP TABLE IF EXISTS SYS_SEMANTIC.OBJECT_PRIVILEGES CASCADE;

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.QUERY_LOG (
  QUERY_LOG_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID              DECIMAL(18,0),
  VERSION_ID            DECIMAL(18,0),
  USER_NAME             VARCHAR(256) DEFAULT CURRENT_USER,
  CLIENT_NAME           VARCHAR(512),
  ORIGINAL_SQL          VARCHAR(2000000),
  GENERATED_SQL         VARCHAR(2000000),
  PLAN_JSON             VARCHAR(2000000),
  REQUESTED_DIMENSIONS  VARCHAR(2000000),
  REQUESTED_METRICS     VARCHAR(2000000),
  MATERIALIZATION_USED  VARCHAR(512),
  STATUS                VARCHAR(64),
  ERROR_CODE            VARCHAR(128),
  ERROR_MESSAGE         VARCHAR(2000000),
  STARTED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FINISHED_AT           TIMESTAMP,
  RUNTIME_MS            DECIMAL(18,0)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.VALIDATION_RUNS (
  VALIDATION_RUN_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID          DECIMAL(18,0),
  VERSION_ID        DECIMAL(18,0),
  MODEL_NAME        VARCHAR(256),
  STATUS            VARCHAR(32) DEFAULT 'RUNNING' NOT NULL,
  STARTED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FINISHED_AT       TIMESTAMP,
  ISSUE_COUNT       DECIMAL(18,0) DEFAULT 0 NOT NULL,
  ERROR_COUNT       DECIMAL(18,0) DEFAULT 0 NOT NULL,
  WARNING_COUNT     DECIMAL(18,0) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.VALIDATION_RESULTS (
  VALIDATION_RESULT_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  VALIDATION_RUN_ID    DECIMAL(18,0) NOT NULL,
  MODEL_ID             DECIMAL(18,0),
  VERSION_ID           DECIMAL(18,0),
  SEVERITY             VARCHAR(32) NOT NULL,
  OBJECT_TYPE          VARCHAR(64) NOT NULL,
  OBJECT_NAME          VARCHAR(512),
  RULE_CODE            VARCHAR(128) NOT NULL,
  MESSAGE              VARCHAR(2000000) NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_DIMENSION_MATRIX (
  MODEL_ID          DECIMAL(18,0) NOT NULL,
  VERSION_ID        DECIMAL(18,0) NOT NULL,
  METRIC_ID         DECIMAL(18,0) NOT NULL,
  DIMENSION_ID      DECIMAL(18,0) NOT NULL,
  IS_VALID          BOOLEAN DEFAULT FALSE NOT NULL,
  REASON_CODE       VARCHAR(128) NOT NULL,
  RELATIONSHIP_PATH VARCHAR(2000000),
  VALIDATION_RUN_ID DECIMAL(18,0),
  UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (MODEL_ID, VERSION_ID, METRIC_ID, DIMENSION_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_PUBLISH_HISTORY (
  PUBLISH_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID         DECIMAL(18,0) NOT NULL,
  VERSION_ID       DECIMAL(18,0) NOT NULL,
  VERSION_NUMBER   DECIMAL(18,0) NOT NULL,
  PUBLISH_NUMBER   DECIMAL(18,0) NOT NULL,
  PUBLISHED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PUBLISHED_BY     VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_ROLE_GRANTS (
  GRANT_ID         DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID         DECIMAL(18,0) NOT NULL,
  MODEL_NAME       VARCHAR(256) NOT NULL,
  ROLE_NAME        VARCHAR(256) NOT NULL,
  PUBLISHED_SCHEMA VARCHAR(256),
  GRANTED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  GRANTED_BY       VARCHAR(256) DEFAULT CURRENT_USER,
  STATUS           VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

-- ============================================================================
-- Retired columns
-- ============================================================================
--
-- CREATE TABLE IF NOT EXISTS is a no-op on an existing catalog, so removing a
-- column from a declaration above does nothing on upgrade. These drops are what
-- actually retires it. Each was a column no code path could ever set -- a
-- promise of behaviour the product does not have, sitting in a catalog an admin
-- reads. DROP COLUMN IF EXISTS is idempotent, and the columns were always NULL,
-- so an upgrade loses nothing.
--
--   MODEL_VERSIONS.CATALOG_HASH   nothing computed it
--   AGENT_FEEDBACK.REVIEWED_AT    a review workflow copied from
--   AGENT_FEEDBACK.REVIEWED_BY    MODEL_EVOLUTION_SUGGESTIONS, where it is real
--                                 (REVIEW_MODEL_EVOLUTION writes both) and never
--                                 built for feedback, which has no review queue
--                                 and no reviewer script.
ALTER TABLE SYS_SEMANTIC.MODEL_VERSIONS DROP COLUMN IF EXISTS CATALOG_HASH;
ALTER TABLE SYS_SEMANTIC.AGENT_FEEDBACK DROP COLUMN IF EXISTS REVIEWED_AT;
ALTER TABLE SYS_SEMANTIC.AGENT_FEEDBACK DROP COLUMN IF EXISTS REVIEWED_BY;

-- ============================================================================
-- Declared foreign keys
-- ============================================================================
--
-- Every join between two catalog tables is now declared as a real FOREIGN KEY
-- constraint rather than living only in the compiler's queries. An agent (or a
-- BI tool, or a person with a fresh psql-shaped mental model) that finds
-- SYS_SEMANTIC and asks "how do these 42 tables connect?" gets the answer from
-- the standard system views instead of reverse-engineering it from Lua:
--
--   SELECT CONSTRAINT_TABLE, COLUMN_NAME, REFERENCED_TABLE, REFERENCED_COLUMN
--   FROM EXA_ALL_CONSTRAINT_COLUMNS
--   WHERE CONSTRAINT_SCHEMA = 'SYS_SEMANTIC' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
--   ORDER BY CONSTRAINT_TABLE, ORDINAL_POSITION;
--
-- SEMANTIC_CATALOG.CATALOG_RELATIONSHIPS wraps that query, adds the view
-- surfaces (which cannot carry constraints) and the discriminated references
-- below, and hands back a ready-to-paste ON clause.
--
-- Every constraint is created DISABLE, deliberately. DISABLE in Exasol means
-- "declared but not enforced": the constraint is fully visible in
-- EXA_ALL_CONSTRAINTS and EXA_ALL_CONSTRAINT_COLUMNS -- which is the whole
-- point, since discoverability is what was missing -- while write semantics
-- stay exactly as they were. Enforcing them would be a different and much
-- larger change, and not a safe one to fold in here:
--
--   * MODELS.ACTIVE_VERSION_ID and MODEL_VERSIONS.MODEL_ID reference each
--     other, so no insert order satisfies both under enforcement.
--   * The catalog soft-deletes via STATUS columns and keeps run/log history
--     (QUERY_LOG, AGENT_REQUEST_LOG, VALIDATION_RUNS) whose parents can be
--     legitimately dropped and rebuilt by a re-publish.
--   * An ENABLE constraint is validated against existing rows on creation, so
--     any deployment carrying a historical orphan would fail to upgrade.
--     A DISABLE constraint installs over existing data unconditionally.
--
-- The DROP CONSTRAINT IF EXISTS before each ADD keeps this section idempotent:
-- 001 runs with CREATE TABLE IF NOT EXISTS, so a re-install over an existing
-- catalog reaches these statements with the tables (and possibly the previous
-- constraints) already in place, and Exasol rejects a duplicate constraint
-- name. Re-running the file therefore re-asserts the current FK map rather
-- than failing or silently skipping tables it did not just create.

-- Model and version scope -- every model-scoped table hangs off these two.
ALTER TABLE SYS_SEMANTIC.SOURCE_TRUST DROP CONSTRAINT IF EXISTS FK_SOURCE_TRUST_MODEL;
ALTER TABLE SYS_SEMANTIC.SOURCE_TRUST ADD CONSTRAINT FK_SOURCE_TRUST_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SOURCE_TRUST DROP CONSTRAINT IF EXISTS FK_SOURCE_TRUST_VERSION;
ALTER TABLE SYS_SEMANTIC.SOURCE_TRUST ADD CONSTRAINT FK_SOURCE_TRUST_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.AGENT_INSTRUCTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_INSTRUCTIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.AGENT_INSTRUCTIONS ADD CONSTRAINT FK_AGENT_INSTRUCTIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.AGENT_INSTRUCTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_INSTRUCTIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.AGENT_INSTRUCTIONS ADD CONSTRAINT FK_AGENT_INSTRUCTIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.AGENT_REQUEST_LOG DROP CONSTRAINT IF EXISTS FK_AGENT_REQUEST_LOG_MODEL;
ALTER TABLE SYS_SEMANTIC.AGENT_REQUEST_LOG ADD CONSTRAINT FK_AGENT_REQUEST_LOG_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.AGENT_REQUEST_LOG DROP CONSTRAINT IF EXISTS FK_AGENT_REQUEST_LOG_VERSION;
ALTER TABLE SYS_SEMANTIC.AGENT_REQUEST_LOG ADD CONSTRAINT FK_AGENT_REQUEST_LOG_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
-- The AGENT_SUGGESTION* tables became MODEL_EVOLUTION_* (tools/install.py
-- renames them in place). Their constraints were renamed with them, so an
-- upgraded catalog has to lose the predecessors by name or it keeps two
-- constraints on the same columns.
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTIONS_AGENT_REQUEST;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTIONS_FEEDBACK;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTIONS_QUERY_LOG;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_REVIEWS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTION_REVIEWS_SUGGESTION;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_TARGETS DROP CONSTRAINT IF EXISTS FK_AGENT_SUGGESTION_TARGETS_SUGGESTION;

ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_SUGGESTIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS ADD CONSTRAINT FK_MODEL_EVOLUTION_SUGGESTIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_SUGGESTIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS ADD CONSTRAINT FK_MODEL_EVOLUTION_SUGGESTIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_BINDINGS_MODEL;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS ADD CONSTRAINT FK_ATTRIBUTE_BINDINGS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_BINDINGS_VERSION;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS ADD CONSTRAINT FK_ATTRIBUTE_BINDINGS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_FUSION_POLICIES_MODEL;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES ADD CONSTRAINT FK_ATTRIBUTE_FUSION_POLICIES_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_FUSION_POLICIES_VERSION;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES ADD CONSTRAINT FK_ATTRIBUTE_FUSION_POLICIES_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.COMPILE_CACHE DROP CONSTRAINT IF EXISTS FK_COMPILE_CACHE_MODEL_VERSION;
ALTER TABLE SYS_SEMANTIC.COMPILE_CACHE ADD CONSTRAINT FK_COMPILE_CACHE_MODEL_VERSION
  FOREIGN KEY (MODEL_VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.CUSTOM_EXTENSIONS DROP CONSTRAINT IF EXISTS FK_CUSTOM_EXTENSIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.CUSTOM_EXTENSIONS ADD CONSTRAINT FK_CUSTOM_EXTENSIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.CUSTOM_EXTENSIONS DROP CONSTRAINT IF EXISTS FK_CUSTOM_EXTENSIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.CUSTOM_EXTENSIONS ADD CONSTRAINT FK_CUSTOM_EXTENSIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.DIMENSIONS DROP CONSTRAINT IF EXISTS FK_DIMENSIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.DIMENSIONS ADD CONSTRAINT FK_DIMENSIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.DIMENSIONS DROP CONSTRAINT IF EXISTS FK_DIMENSIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.DIMENSIONS ADD CONSTRAINT FK_DIMENSIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ENTITIES DROP CONSTRAINT IF EXISTS FK_ENTITIES_MODEL;
ALTER TABLE SYS_SEMANTIC.ENTITIES ADD CONSTRAINT FK_ENTITIES_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ENTITIES DROP CONSTRAINT IF EXISTS FK_ENTITIES_VERSION;
ALTER TABLE SYS_SEMANTIC.ENTITIES ADD CONSTRAINT FK_ENTITIES_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ENTITY_REPRESENTATIONS DROP CONSTRAINT IF EXISTS FK_ENTITY_REPRESENTATIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.ENTITY_REPRESENTATIONS ADD CONSTRAINT FK_ENTITY_REPRESENTATIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ENTITY_REPRESENTATIONS DROP CONSTRAINT IF EXISTS FK_ENTITY_REPRESENTATIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.ENTITY_REPRESENTATIONS ADD CONSTRAINT FK_ENTITY_REPRESENTATIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.FACTS DROP CONSTRAINT IF EXISTS FK_FACTS_MODEL;
ALTER TABLE SYS_SEMANTIC.FACTS ADD CONSTRAINT FK_FACTS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.FACTS DROP CONSTRAINT IF EXISTS FK_FACTS_VERSION;
ALTER TABLE SYS_SEMANTIC.FACTS ADD CONSTRAINT FK_FACTS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS DROP CONSTRAINT IF EXISTS FK_IDENTITY_BINDINGS_MODEL;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS ADD CONSTRAINT FK_IDENTITY_BINDINGS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS DROP CONSTRAINT IF EXISTS FK_IDENTITY_BINDINGS_VERSION;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS ADD CONSTRAINT FK_IDENTITY_BINDINGS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS DROP CONSTRAINT IF EXISTS FK_IDENTITY_MAPPING_RELATIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS ADD CONSTRAINT FK_IDENTITY_MAPPING_RELATIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS DROP CONSTRAINT IF EXISTS FK_IDENTITY_MAPPING_RELATIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS ADD CONSTRAINT FK_IDENTITY_MAPPING_RELATIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MATERIALIZATIONS DROP CONSTRAINT IF EXISTS FK_MATERIALIZATIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.MATERIALIZATIONS ADD CONSTRAINT FK_MATERIALIZATIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MATERIALIZATIONS DROP CONSTRAINT IF EXISTS FK_MATERIALIZATIONS_VERSION;
ALTER TABLE SYS_SEMANTIC.MATERIALIZATIONS ADD CONSTRAINT FK_MATERIALIZATIONS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRICS DROP CONSTRAINT IF EXISTS FK_METRICS_MODEL;
ALTER TABLE SYS_SEMANTIC.METRICS ADD CONSTRAINT FK_METRICS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRICS DROP CONSTRAINT IF EXISTS FK_METRICS_VERSION;
ALTER TABLE SYS_SEMANTIC.METRICS ADD CONSTRAINT FK_METRICS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX DROP CONSTRAINT IF EXISTS FK_METRIC_DIMENSION_MATRIX_MODEL;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX ADD CONSTRAINT FK_METRIC_DIMENSION_MATRIX_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX DROP CONSTRAINT IF EXISTS FK_METRIC_DIMENSION_MATRIX_VERSION;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX ADD CONSTRAINT FK_METRIC_DIMENSION_MATRIX_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODELS DROP CONSTRAINT IF EXISTS FK_MODELS_ACTIVE_VERSION;
ALTER TABLE SYS_SEMANTIC.MODELS ADD CONSTRAINT FK_MODELS_ACTIVE_VERSION
  FOREIGN KEY (ACTIVE_VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_PUBLISH_HISTORY DROP CONSTRAINT IF EXISTS FK_MODEL_PUBLISH_HISTORY_MODEL;
ALTER TABLE SYS_SEMANTIC.MODEL_PUBLISH_HISTORY ADD CONSTRAINT FK_MODEL_PUBLISH_HISTORY_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_PUBLISH_HISTORY DROP CONSTRAINT IF EXISTS FK_MODEL_PUBLISH_HISTORY_VERSION;
ALTER TABLE SYS_SEMANTIC.MODEL_PUBLISH_HISTORY ADD CONSTRAINT FK_MODEL_PUBLISH_HISTORY_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_ROLE_GRANTS DROP CONSTRAINT IF EXISTS FK_MODEL_ROLE_GRANTS_MODEL;
ALTER TABLE SYS_SEMANTIC.MODEL_ROLE_GRANTS ADD CONSTRAINT FK_MODEL_ROLE_GRANTS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_VERSIONS DROP CONSTRAINT IF EXISTS FK_MODEL_VERSIONS_MODEL;
ALTER TABLE SYS_SEMANTIC.MODEL_VERSIONS ADD CONSTRAINT FK_MODEL_VERSIONS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.QUERY_LOG DROP CONSTRAINT IF EXISTS FK_QUERY_LOG_MODEL;
ALTER TABLE SYS_SEMANTIC.QUERY_LOG ADD CONSTRAINT FK_QUERY_LOG_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.QUERY_LOG DROP CONSTRAINT IF EXISTS FK_QUERY_LOG_VERSION;
ALTER TABLE SYS_SEMANTIC.QUERY_LOG ADD CONSTRAINT FK_QUERY_LOG_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS DROP CONSTRAINT IF EXISTS FK_RELATIONSHIPS_MODEL;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS ADD CONSTRAINT FK_RELATIONSHIPS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS DROP CONSTRAINT IF EXISTS FK_RELATIONSHIPS_VERSION;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS ADD CONSTRAINT FK_RELATIONSHIPS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES DROP CONSTRAINT IF EXISTS FK_REPRESENTATION_AUTHORITIES_MODEL;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES ADD CONSTRAINT FK_REPRESENTATION_AUTHORITIES_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES DROP CONSTRAINT IF EXISTS FK_REPRESENTATION_AUTHORITIES_VERSION;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES ADD CONSTRAINT FK_REPRESENTATION_AUTHORITIES_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES DROP CONSTRAINT IF EXISTS FK_SEMANTIC_DEFINITION_SOURCES_MODEL;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES ADD CONSTRAINT FK_SEMANTIC_DEFINITION_SOURCES_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES DROP CONSTRAINT IF EXISTS FK_SEMANTIC_DEFINITION_SOURCES_VERSION;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES ADD CONSTRAINT FK_SEMANTIC_DEFINITION_SOURCES_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_IDENTITIES DROP CONSTRAINT IF EXISTS FK_SEMANTIC_IDENTITIES_MODEL;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_IDENTITIES ADD CONSTRAINT FK_SEMANTIC_IDENTITIES_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_IDENTITIES DROP CONSTRAINT IF EXISTS FK_SEMANTIC_IDENTITIES_VERSION;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_IDENTITIES ADD CONSTRAINT FK_SEMANTIC_IDENTITIES_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_OBJECTS DROP CONSTRAINT IF EXISTS FK_SEMANTIC_OBJECTS_MODEL;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_OBJECTS ADD CONSTRAINT FK_SEMANTIC_OBJECTS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_OBJECTS DROP CONSTRAINT IF EXISTS FK_SEMANTIC_OBJECTS_VERSION;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_OBJECTS ADD CONSTRAINT FK_SEMANTIC_OBJECTS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SYNONYMS DROP CONSTRAINT IF EXISTS FK_SYNONYMS_MODEL;
ALTER TABLE SYS_SEMANTIC.SYNONYMS ADD CONSTRAINT FK_SYNONYMS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SYNONYMS DROP CONSTRAINT IF EXISTS FK_SYNONYMS_VERSION;
ALTER TABLE SYS_SEMANTIC.SYNONYMS ADD CONSTRAINT FK_SYNONYMS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEYS DROP CONSTRAINT IF EXISTS FK_UNIQUE_KEYS_MODEL;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEYS ADD CONSTRAINT FK_UNIQUE_KEYS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEYS DROP CONSTRAINT IF EXISTS FK_UNIQUE_KEYS_VERSION;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEYS ADD CONSTRAINT FK_UNIQUE_KEYS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RESULTS DROP CONSTRAINT IF EXISTS FK_VALIDATION_RESULTS_MODEL;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RESULTS ADD CONSTRAINT FK_VALIDATION_RESULTS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RESULTS DROP CONSTRAINT IF EXISTS FK_VALIDATION_RESULTS_VERSION;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RESULTS ADD CONSTRAINT FK_VALIDATION_RESULTS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RUNS DROP CONSTRAINT IF EXISTS FK_VALIDATION_RUNS_MODEL;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RUNS ADD CONSTRAINT FK_VALIDATION_RUNS_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RUNS DROP CONSTRAINT IF EXISTS FK_VALIDATION_RUNS_VERSION;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RUNS ADD CONSTRAINT FK_VALIDATION_RUNS_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VERIFIED_QUERIES DROP CONSTRAINT IF EXISTS FK_VERIFIED_QUERIES_MODEL;
ALTER TABLE SYS_SEMANTIC.VERIFIED_QUERIES ADD CONSTRAINT FK_VERIFIED_QUERIES_MODEL
  FOREIGN KEY (MODEL_ID) REFERENCES SYS_SEMANTIC.MODELS (MODEL_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VERIFIED_QUERIES DROP CONSTRAINT IF EXISTS FK_VERIFIED_QUERIES_VERSION;
ALTER TABLE SYS_SEMANTIC.VERIFIED_QUERIES ADD CONSTRAINT FK_VERIFIED_QUERIES_VERSION
  FOREIGN KEY (VERSION_ID) REFERENCES SYS_SEMANTIC.MODEL_VERSIONS (VERSION_ID) DISABLE;

-- Entity, representation, and key structure.
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_BINDINGS_ENTITY;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS ADD CONSTRAINT FK_ATTRIBUTE_BINDINGS_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_BINDINGS_REPRESENTATION;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS ADD CONSTRAINT FK_ATTRIBUTE_BINDINGS_REPRESENTATION
  FOREIGN KEY (REPRESENTATION_ID) REFERENCES SYS_SEMANTIC.ENTITY_REPRESENTATIONS (REPRESENTATION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES DROP CONSTRAINT IF EXISTS FK_ATTRIBUTE_FUSION_POLICIES_ENTITY;
ALTER TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES ADD CONSTRAINT FK_ATTRIBUTE_FUSION_POLICIES_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.DIMENSIONS DROP CONSTRAINT IF EXISTS FK_DIMENSIONS_ENTITY;
ALTER TABLE SYS_SEMANTIC.DIMENSIONS ADD CONSTRAINT FK_DIMENSIONS_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.ENTITY_REPRESENTATIONS DROP CONSTRAINT IF EXISTS FK_ENTITY_REPRESENTATIONS_ENTITY;
ALTER TABLE SYS_SEMANTIC.ENTITY_REPRESENTATIONS ADD CONSTRAINT FK_ENTITY_REPRESENTATIONS_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.FACTS DROP CONSTRAINT IF EXISTS FK_FACTS_ENTITY;
ALTER TABLE SYS_SEMANTIC.FACTS ADD CONSTRAINT FK_FACTS_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS DROP CONSTRAINT IF EXISTS FK_IDENTITY_BINDINGS_ENTITY;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS ADD CONSTRAINT FK_IDENTITY_BINDINGS_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS DROP CONSTRAINT IF EXISTS FK_IDENTITY_BINDINGS_IDENTITY;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS ADD CONSTRAINT FK_IDENTITY_BINDINGS_IDENTITY
  FOREIGN KEY (IDENTITY_ID) REFERENCES SYS_SEMANTIC.SEMANTIC_IDENTITIES (IDENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS DROP CONSTRAINT IF EXISTS FK_IDENTITY_BINDINGS_REPRESENTATION;
ALTER TABLE SYS_SEMANTIC.IDENTITY_BINDINGS ADD CONSTRAINT FK_IDENTITY_BINDINGS_REPRESENTATION
  FOREIGN KEY (REPRESENTATION_ID) REFERENCES SYS_SEMANTIC.ENTITY_REPRESENTATIONS (REPRESENTATION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS DROP CONSTRAINT IF EXISTS FK_IDENTITY_MAPPING_RELATIONS_IDENTITY_BINDING;
ALTER TABLE SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS ADD CONSTRAINT FK_IDENTITY_MAPPING_RELATIONS_IDENTITY_BINDING
  FOREIGN KEY (IDENTITY_BINDING_ID) REFERENCES SYS_SEMANTIC.IDENTITY_BINDINGS (IDENTITY_BINDING_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRICS DROP CONSTRAINT IF EXISTS FK_METRICS_BASE_ENTITY;
ALTER TABLE SYS_SEMANTIC.METRICS ADD CONSTRAINT FK_METRICS_BASE_ENTITY
  FOREIGN KEY (BASE_ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_FILTERS DROP CONSTRAINT IF EXISTS FK_METRIC_FILTERS_REQUIRED_ENTITY;
ALTER TABLE SYS_SEMANTIC.METRIC_FILTERS ADD CONSTRAINT FK_METRIC_FILTERS_REQUIRED_ENTITY
  FOREIGN KEY (REQUIRED_ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS DROP CONSTRAINT IF EXISTS FK_RELATIONSHIPS_FROM_ENTITY;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS ADD CONSTRAINT FK_RELATIONSHIPS_FROM_ENTITY
  FOREIGN KEY (FROM_ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS DROP CONSTRAINT IF EXISTS FK_RELATIONSHIPS_TO_ENTITY;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIPS ADD CONSTRAINT FK_RELATIONSHIPS_TO_ENTITY
  FOREIGN KEY (TO_ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES DROP CONSTRAINT IF EXISTS FK_REPRESENTATION_AUTHORITIES_ENTITY;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES ADD CONSTRAINT FK_REPRESENTATION_AUTHORITIES_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES DROP CONSTRAINT IF EXISTS FK_REPRESENTATION_AUTHORITIES_REPRESENTATION;
ALTER TABLE SYS_SEMANTIC.REPRESENTATION_AUTHORITIES ADD CONSTRAINT FK_REPRESENTATION_AUTHORITIES_REPRESENTATION
  FOREIGN KEY (REPRESENTATION_ID) REFERENCES SYS_SEMANTIC.ENTITY_REPRESENTATIONS (REPRESENTATION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_IDENTITIES DROP CONSTRAINT IF EXISTS FK_SEMANTIC_IDENTITIES_ENTITY;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_IDENTITIES ADD CONSTRAINT FK_SEMANTIC_IDENTITIES_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_OBJECTS DROP CONSTRAINT IF EXISTS FK_SEMANTIC_OBJECTS_ROOT_ENTITY;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_OBJECTS ADD CONSTRAINT FK_SEMANTIC_OBJECTS_ROOT_ENTITY
  FOREIGN KEY (ROOT_ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEYS DROP CONSTRAINT IF EXISTS FK_UNIQUE_KEYS_ENTITY;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEYS ADD CONSTRAINT FK_UNIQUE_KEYS_ENTITY
  FOREIGN KEY (ENTITY_ID) REFERENCES SYS_SEMANTIC.ENTITIES (ENTITY_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEY_COLUMNS DROP CONSTRAINT IF EXISTS FK_UNIQUE_KEY_COLUMNS_UNIQUE_KEY;
ALTER TABLE SYS_SEMANTIC.UNIQUE_KEY_COLUMNS ADD CONSTRAINT FK_UNIQUE_KEY_COLUMNS_UNIQUE_KEY
  FOREIGN KEY (UNIQUE_KEY_ID) REFERENCES SYS_SEMANTIC.UNIQUE_KEYS (UNIQUE_KEY_ID) DISABLE;

-- Semantic objects, relationships, and their detail rows.
ALTER TABLE SYS_SEMANTIC.MATERIALIZATION_COLUMNS DROP CONSTRAINT IF EXISTS FK_MATERIALIZATION_COLUMNS_MATERIALIZATION;
ALTER TABLE SYS_SEMANTIC.MATERIALIZATION_COLUMNS ADD CONSTRAINT FK_MATERIALIZATION_COLUMNS_MATERIALIZATION
  FOREIGN KEY (MATERIALIZATION_ID) REFERENCES SYS_SEMANTIC.MATERIALIZATIONS (MATERIALIZATION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.OBJECT_COLUMNS DROP CONSTRAINT IF EXISTS FK_OBJECT_COLUMNS_SEMANTIC_OBJECT;
ALTER TABLE SYS_SEMANTIC.OBJECT_COLUMNS ADD CONSTRAINT FK_OBJECT_COLUMNS_SEMANTIC_OBJECT
  FOREIGN KEY (OBJECT_ID) REFERENCES SYS_SEMANTIC.SEMANTIC_OBJECTS (OBJECT_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIP_KEY_MAPPINGS DROP CONSTRAINT IF EXISTS FK_RELATIONSHIP_KEY_MAPPINGS_RELATIONSHIP;
ALTER TABLE SYS_SEMANTIC.RELATIONSHIP_KEY_MAPPINGS ADD CONSTRAINT FK_RELATIONSHIP_KEY_MAPPINGS_RELATIONSHIP
  FOREIGN KEY (RELATIONSHIP_ID) REFERENCES SYS_SEMANTIC.RELATIONSHIPS (RELATIONSHIP_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VERIFIED_QUERIES DROP CONSTRAINT IF EXISTS FK_VERIFIED_QUERIES_SEMANTIC_OBJECT;
ALTER TABLE SYS_SEMANTIC.VERIFIED_QUERIES ADD CONSTRAINT FK_VERIFIED_QUERIES_SEMANTIC_OBJECT
  FOREIGN KEY (OBJECT_ID) REFERENCES SYS_SEMANTIC.SEMANTIC_OBJECTS (OBJECT_ID) DISABLE;

-- Metric graph: dependencies, inputs, filters, and compatibility.
ALTER TABLE SYS_SEMANTIC.METRICS DROP CONSTRAINT IF EXISTS FK_METRICS_DEFINITION_SOURCE;
ALTER TABLE SYS_SEMANTIC.METRICS ADD CONSTRAINT FK_METRICS_DEFINITION_SOURCE
  FOREIGN KEY (DEFINITION_SOURCE_ID) REFERENCES SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES (DEFINITION_SOURCE_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRICS DROP CONSTRAINT IF EXISTS FK_METRICS_NON_ADDITIVE_DIMENSION;
ALTER TABLE SYS_SEMANTIC.METRICS ADD CONSTRAINT FK_METRICS_NON_ADDITIVE_DIMENSION
  FOREIGN KEY (NON_ADDITIVE_DIMENSION_ID) REFERENCES SYS_SEMANTIC.DIMENSIONS (DIMENSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_DEPENDENCIES DROP CONSTRAINT IF EXISTS FK_METRIC_DEPENDENCIES_METRIC;
ALTER TABLE SYS_SEMANTIC.METRIC_DEPENDENCIES ADD CONSTRAINT FK_METRIC_DEPENDENCIES_METRIC
  FOREIGN KEY (METRIC_ID) REFERENCES SYS_SEMANTIC.METRICS (METRIC_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX DROP CONSTRAINT IF EXISTS FK_METRIC_DIMENSION_MATRIX_DIMENSION;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX ADD CONSTRAINT FK_METRIC_DIMENSION_MATRIX_DIMENSION
  FOREIGN KEY (DIMENSION_ID) REFERENCES SYS_SEMANTIC.DIMENSIONS (DIMENSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX DROP CONSTRAINT IF EXISTS FK_METRIC_DIMENSION_MATRIX_METRIC;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX ADD CONSTRAINT FK_METRIC_DIMENSION_MATRIX_METRIC
  FOREIGN KEY (METRIC_ID) REFERENCES SYS_SEMANTIC.METRICS (METRIC_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_FILTERS DROP CONSTRAINT IF EXISTS FK_METRIC_FILTERS_METRIC;
ALTER TABLE SYS_SEMANTIC.METRIC_FILTERS ADD CONSTRAINT FK_METRIC_FILTERS_METRIC
  FOREIGN KEY (METRIC_ID) REFERENCES SYS_SEMANTIC.METRICS (METRIC_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_FILTERS DROP CONSTRAINT IF EXISTS FK_METRIC_FILTERS_REQUIRED_DIMENSION;
ALTER TABLE SYS_SEMANTIC.METRIC_FILTERS ADD CONSTRAINT FK_METRIC_FILTERS_REQUIRED_DIMENSION
  FOREIGN KEY (REQUIRED_DIMENSION_ID) REFERENCES SYS_SEMANTIC.DIMENSIONS (DIMENSION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_INPUTS DROP CONSTRAINT IF EXISTS FK_METRIC_INPUTS_METRIC;
ALTER TABLE SYS_SEMANTIC.METRIC_INPUTS ADD CONSTRAINT FK_METRIC_INPUTS_METRIC
  FOREIGN KEY (METRIC_ID) REFERENCES SYS_SEMANTIC.METRICS (METRIC_ID) DISABLE;

-- Validation and compile lineage.
ALTER TABLE SYS_SEMANTIC.COMPILE_CACHE DROP CONSTRAINT IF EXISTS FK_COMPILE_CACHE_VALIDATION_RUN;
ALTER TABLE SYS_SEMANTIC.COMPILE_CACHE ADD CONSTRAINT FK_COMPILE_CACHE_VALIDATION_RUN
  FOREIGN KEY (VALIDATION_RUN_ID) REFERENCES SYS_SEMANTIC.VALIDATION_RUNS (VALIDATION_RUN_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX DROP CONSTRAINT IF EXISTS FK_METRIC_DIMENSION_MATRIX_VALIDATION_RUN;
ALTER TABLE SYS_SEMANTIC.METRIC_DIMENSION_MATRIX ADD CONSTRAINT FK_METRIC_DIMENSION_MATRIX_VALIDATION_RUN
  FOREIGN KEY (VALIDATION_RUN_ID) REFERENCES SYS_SEMANTIC.VALIDATION_RUNS (VALIDATION_RUN_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES DROP CONSTRAINT IF EXISTS FK_SEMANTIC_DEFINITION_SOURCES_VALIDATION_RUN;
ALTER TABLE SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES ADD CONSTRAINT FK_SEMANTIC_DEFINITION_SOURCES_VALIDATION_RUN
  FOREIGN KEY (VALIDATION_RUN_ID) REFERENCES SYS_SEMANTIC.VALIDATION_RUNS (VALIDATION_RUN_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RESULTS DROP CONSTRAINT IF EXISTS FK_VALIDATION_RESULTS_VALIDATION_RUN;
ALTER TABLE SYS_SEMANTIC.VALIDATION_RESULTS ADD CONSTRAINT FK_VALIDATION_RESULTS_VALIDATION_RUN
  FOREIGN KEY (VALIDATION_RUN_ID) REFERENCES SYS_SEMANTIC.VALIDATION_RUNS (VALIDATION_RUN_ID) DISABLE;

-- Agent request, feedback, and suggestion loop.
ALTER TABLE SYS_SEMANTIC.AGENT_FEEDBACK DROP CONSTRAINT IF EXISTS FK_AGENT_FEEDBACK_AGENT_REQUEST;
ALTER TABLE SYS_SEMANTIC.AGENT_FEEDBACK ADD CONSTRAINT FK_AGENT_FEEDBACK_AGENT_REQUEST
  FOREIGN KEY (AGENT_REQUEST_ID) REFERENCES SYS_SEMANTIC.AGENT_REQUEST_LOG (AGENT_REQUEST_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.AGENT_FEEDBACK DROP CONSTRAINT IF EXISTS FK_AGENT_FEEDBACK_QUERY_LOG;
ALTER TABLE SYS_SEMANTIC.AGENT_FEEDBACK ADD CONSTRAINT FK_AGENT_FEEDBACK_QUERY_LOG
  FOREIGN KEY (QUERY_LOG_ID) REFERENCES SYS_SEMANTIC.QUERY_LOG (QUERY_LOG_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_SUGGESTIONS_AGENT_REQUEST;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS ADD CONSTRAINT FK_MODEL_EVOLUTION_SUGGESTIONS_AGENT_REQUEST
  FOREIGN KEY (AGENT_REQUEST_ID) REFERENCES SYS_SEMANTIC.AGENT_REQUEST_LOG (AGENT_REQUEST_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_SUGGESTIONS_FEEDBACK;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS ADD CONSTRAINT FK_MODEL_EVOLUTION_SUGGESTIONS_FEEDBACK
  FOREIGN KEY (FEEDBACK_ID) REFERENCES SYS_SEMANTIC.AGENT_FEEDBACK (FEEDBACK_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_SUGGESTIONS_QUERY_LOG;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS ADD CONSTRAINT FK_MODEL_EVOLUTION_SUGGESTIONS_QUERY_LOG
  FOREIGN KEY (QUERY_LOG_ID) REFERENCES SYS_SEMANTIC.QUERY_LOG (QUERY_LOG_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_REVIEWS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_REVIEWS_SUGGESTION;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_REVIEWS ADD CONSTRAINT FK_MODEL_EVOLUTION_REVIEWS_SUGGESTION
  FOREIGN KEY (SUGGESTION_ID) REFERENCES SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS (SUGGESTION_ID) DISABLE;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_TARGETS DROP CONSTRAINT IF EXISTS FK_MODEL_EVOLUTION_TARGETS_SUGGESTION;
ALTER TABLE SYS_SEMANTIC.MODEL_EVOLUTION_TARGETS ADD CONSTRAINT FK_MODEL_EVOLUTION_TARGETS_SUGGESTION
  FOREIGN KEY (SUGGESTION_ID) REFERENCES SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS (SUGGESTION_ID) DISABLE;

-- ── Discriminated (polymorphic) references ───────────────────────────────────
--
-- These columns are foreign keys in every sense except the one SQL can
-- express: the table they point at is chosen at runtime by a sibling
-- discriminator column, so no single REFERENCES clause is correct and Exasol
-- cannot declare the constraint. Left undocumented they are the worst case for
-- an exploring agent -- a bare DECIMAL that looks unrelated to anything -- so
-- each one is described here instead. Column comments surface automatically in
-- SEMANTIC_CATALOG.CATALOG_COLUMNS.DESCRIPTION and in the DISCRIMINATED rows of
-- SEMANTIC_CATALOG.CATALOG_RELATIONSHIPS, so this text is reachable by query
-- and not only by reading this file.

COMMENT ON TABLE SYS_SEMANTIC.OBJECT_COLUMNS (
  COLUMN_KIND IS 'Discriminator for OBJECT_REF_ID. One of DIMENSION, FACT, METRIC.',
  OBJECT_REF_ID IS 'Discriminated reference resolved by COLUMN_KIND: DIMENSION -> DIMENSIONS.DIMENSION_ID, FACT -> FACTS.FACT_ID, METRIC -> METRICS.METRIC_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.METRIC_DEPENDENCIES (
  DEPENDS_ON_OBJECT_TYPE IS 'Discriminator for DEPENDS_ON_OBJECT_ID. One of FACT, METRIC.',
  DEPENDS_ON_OBJECT_ID IS 'Discriminated reference resolved by DEPENDS_ON_OBJECT_TYPE: FACT -> FACTS.FACT_ID, METRIC -> METRICS.METRIC_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.METRIC_INPUTS (
  INPUT_OBJECT_TYPE IS 'Discriminator for INPUT_OBJECT_ID. One of FACT, METRIC.',
  INPUT_OBJECT_ID IS 'Discriminated reference resolved by INPUT_OBJECT_TYPE: FACT -> FACTS.FACT_ID, METRIC -> METRICS.METRIC_ID. NULL when the input is a literal expression rather than a catalog object.'
);

COMMENT ON TABLE SYS_SEMANTIC.ATTRIBUTE_BINDINGS (
  ATTRIBUTE_TYPE IS 'Discriminator for ATTRIBUTE_ID. One of DIMENSION, FACT.',
  ATTRIBUTE_ID IS 'Discriminated reference resolved by ATTRIBUTE_TYPE: DIMENSION -> DIMENSIONS.DIMENSION_ID, FACT -> FACTS.FACT_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES (
  ATTRIBUTE_TYPE IS 'Discriminator for ATTRIBUTE_ID. One of DIMENSION, FACT.',
  ATTRIBUTE_ID IS 'Discriminated reference resolved by ATTRIBUTE_TYPE: DIMENSION -> DIMENSIONS.DIMENSION_ID, FACT -> FACTS.FACT_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.SYNONYMS (
  OBJECT_TYPE IS 'Discriminator for OBJECT_ID. DIMENSION or METRIC in practice; imported models may carry other catalog object types.',
  OBJECT_ID IS 'Discriminated reference resolved by OBJECT_TYPE: DIMENSION -> DIMENSIONS.DIMENSION_ID, METRIC -> METRICS.METRIC_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.CUSTOM_EXTENSIONS (
  SCOPE_TYPE IS 'Discriminator for SCOPE_ID. One of MODEL, SEMANTIC_OBJECT, ENTITY, RELATIONSHIP, DIMENSION, FACT, METRIC.',
  SCOPE_ID IS 'Discriminated reference resolved by SCOPE_TYPE: MODEL -> MODELS.MODEL_ID, SEMANTIC_OBJECT -> SEMANTIC_OBJECTS.OBJECT_ID, ENTITY -> ENTITIES.ENTITY_ID, RELATIONSHIP -> RELATIONSHIPS.RELATIONSHIP_ID, DIMENSION -> DIMENSIONS.DIMENSION_ID, FACT -> FACTS.FACT_ID, METRIC -> METRICS.METRIC_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.AGENT_INSTRUCTIONS (
  SCOPE_TYPE IS 'Discriminator for SCOPE_ID. One of MODEL, SEMANTIC_OBJECT, ENTITY, DIMENSION, FACT, METRIC.',
  SCOPE_ID IS 'Discriminated reference resolved by SCOPE_TYPE: MODEL -> MODELS.MODEL_ID, SEMANTIC_OBJECT -> SEMANTIC_OBJECTS.OBJECT_ID, ENTITY -> ENTITIES.ENTITY_ID, DIMENSION -> DIMENSIONS.DIMENSION_ID, FACT -> FACTS.FACT_ID, METRIC -> METRICS.METRIC_ID. NULL means the instruction applies to the whole model.'
);

COMMENT ON TABLE SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS (
  OBJECT_TYPE IS 'Discriminator for OBJECT_ID. One of MODEL, SEMANTIC_OBJECT, ENTITY, RELATIONSHIP, DIMENSION, FACT, METRIC, SEMANTIC_IDENTITY.',
  OBJECT_ID IS 'Discriminated reference resolved by OBJECT_TYPE: MODEL -> MODELS.MODEL_ID, SEMANTIC_OBJECT -> SEMANTIC_OBJECTS.OBJECT_ID, ENTITY -> ENTITIES.ENTITY_ID, RELATIONSHIP -> RELATIONSHIPS.RELATIONSHIP_ID, DIMENSION -> DIMENSIONS.DIMENSION_ID, FACT -> FACTS.FACT_ID, METRIC -> METRICS.METRIC_ID, SEMANTIC_IDENTITY -> SEMANTIC_IDENTITIES.IDENTITY_ID. NULL for a NEW_CONCEPT suggestion, whose target does not exist yet -- read MODEL_EVOLUTION_TARGETS.OBJECT_NAME instead.'
);

COMMENT ON TABLE SYS_SEMANTIC.MATERIALIZATION_COLUMNS (
  OBJECT_TYPE IS 'Discriminator for OBJECT_ID. One of DIMENSION, METRIC.',
  OBJECT_ID IS 'Discriminated reference resolved by OBJECT_TYPE: DIMENSION -> DIMENSIONS.DIMENSION_ID, METRIC -> METRICS.METRIC_ID.'
);

COMMENT ON TABLE SYS_SEMANTIC.VALIDATION_RESULTS (
  OBJECT_TYPE IS 'Kind of catalog object the issue was raised against (ENTITY, DIMENSION, FACT, METRIC, RELATIONSHIP, SEMANTIC_OBJECT, and other catalog object kinds).',
  OBJECT_NAME IS 'Name -- not id -- of the offending object. Validation results are recorded by name so an issue survives the object being dropped, which is why there is no id column to declare a foreign key on. Join back through the name column of the table named by OBJECT_TYPE.'
);
