CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODELS (
  MODEL_ID             DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_NAME           VARCHAR(256) NOT NULL,
  PUBLISHED_SCHEMA     VARCHAR(256),
  DESCRIPTION          VARCHAR(2000000),
  OWNER_ROLE           VARCHAR(256),
  STATUS               VARCHAR(32) DEFAULT 'DRAFT' NOT NULL,
  ACTIVE_VERSION_ID    DECIMAL(18,0),
  PREPROCESSOR_SCHEMA  VARCHAR(256),
  PREPROCESSOR_SCRIPT  VARCHAR(256),
  SURFACE_TYPE         VARCHAR(32) DEFAULT 'VIEW_PREPROCESSOR',
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  UPDATED_AT           TIMESTAMP,
  UPDATED_BY           VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_VERSIONS (
  VERSION_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID         DECIMAL(18,0) NOT NULL,
  VERSION_NUMBER   DECIMAL(18,0) NOT NULL,
  VERSION_LABEL    VARCHAR(256),
  STATUS           VARCHAR(32) DEFAULT 'DRAFT' NOT NULL,
  CHANGE_SUMMARY   VARCHAR(2000000),
  CATALOG_HASH     VARCHAR(128),
  CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY       VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.ENTITIES (
  ENTITY_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_NAME        VARCHAR(256) NOT NULL,
  SOURCE_SCHEMA      VARCHAR(256) NOT NULL,
  SOURCE_OBJECT      VARCHAR(256) NOT NULL,
  SOURCE_ALIAS       VARCHAR(128) NOT NULL,
  PRIMARY_KEY_EXPR   VARCHAR(2000000),
  GRAIN_DESCRIPTION  VARCHAR(2000000),
  DESCRIPTION        VARCHAR(2000000),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SEMANTIC_OBJECTS (
  OBJECT_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  OBJECT_NAME        VARCHAR(256) NOT NULL,
  ROOT_ENTITY_ID     DECIMAL(18,0),
  DESCRIPTION        VARCHAR(2000000),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.RELATIONSHIPS (
  RELATIONSHIP_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  RELATIONSHIP_NAME  VARCHAR(256) NOT NULL,
  FROM_ENTITY_ID     DECIMAL(18,0) NOT NULL,
  TO_ENTITY_ID       DECIMAL(18,0) NOT NULL,
  JOIN_CONDITION     VARCHAR(2000000) NOT NULL,
  RELATIONSHIP_CARDINALITY VARCHAR(64) NOT NULL,
  JOIN_TYPE          VARCHAR(32) DEFAULT 'LEFT' NOT NULL,
  IS_REQUIRED        BOOLEAN DEFAULT FALSE,
  FANOUT_POLICY      VARCHAR(64),
  PATH_PRIORITY      DECIMAL(18,0) DEFAULT 100,
  DESCRIPTION        VARCHAR(2000000),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.DIMENSIONS (
  DIMENSION_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_ID          DECIMAL(18,0) NOT NULL,
  DIMENSION_NAME     VARCHAR(256) NOT NULL,
  EXPRESSION         VARCHAR(2000000) NOT NULL,
  DATA_TYPE          VARCHAR(128) NOT NULL,
  DISPLAY_NAME       VARCHAR(512),
  DESCRIPTION        VARCHAR(2000000),
  FORMAT_HINT        VARCHAR(512),
  UNIT_HINT          VARCHAR(256),
  SENSITIVITY_LABEL  VARCHAR(256),
  DISPLAY_POLICY     VARCHAR(512),
  IS_HIDDEN          BOOLEAN DEFAULT FALSE,
  IS_CERTIFIED       BOOLEAN DEFAULT FALSE,
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.FACTS (
  FACT_ID            DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  ENTITY_ID          DECIMAL(18,0) NOT NULL,
  FACT_NAME          VARCHAR(256) NOT NULL,
  EXPRESSION         VARCHAR(2000000) NOT NULL,
  DATA_TYPE          VARCHAR(128) NOT NULL,
  ADDITIVE_POLICY    VARCHAR(64) DEFAULT 'ADDITIVE' NOT NULL,
  DISPLAY_NAME       VARCHAR(512),
  DESCRIPTION        VARCHAR(2000000),
  FORMAT_HINT        VARCHAR(512),
  UNIT_HINT          VARCHAR(256),
  SENSITIVITY_LABEL  VARCHAR(256),
  DISPLAY_POLICY     VARCHAR(512),
  IS_PRIVATE         BOOLEAN DEFAULT FALSE,
  IS_CERTIFIED       BOOLEAN DEFAULT FALSE,
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRICS (
  METRIC_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID           DECIMAL(18,0) NOT NULL,
  VERSION_ID         DECIMAL(18,0) NOT NULL,
  METRIC_NAME        VARCHAR(256) NOT NULL,
  EXPRESSION         VARCHAR(2000000) NOT NULL,
  FILTER_EXPR        VARCHAR(2000000),
  METRIC_TYPE        VARCHAR(64) NOT NULL,
  BASE_ENTITY_ID     DECIMAL(18,0),
  DATA_TYPE          VARCHAR(128) NOT NULL,
  DISPLAY_NAME       VARCHAR(512),
  DESCRIPTION        VARCHAR(2000000),
  FORMAT_HINT        VARCHAR(512),
  UNIT_HINT          VARCHAR(256),
  SENSITIVITY_LABEL  VARCHAR(256),
  DISPLAY_POLICY     VARCHAR(512),
  IS_PRIVATE         BOOLEAN DEFAULT FALSE,
  IS_CERTIFIED       BOOLEAN DEFAULT FALSE,
  OWNER_ROLE         VARCHAR(256),
  METRIC_KIND        VARCHAR(64),
  AGGREGATION_FUNCTION VARCHAR(64),
  MEASURE_EXPR       VARCHAR(2000000),
  SEMANTIC_FILTER_EXPR VARCHAR(2000000),
  SQL_FILTER_EXPR    VARCHAR(2000000),
  DISTINCT_KEY_EXPR  VARCHAR(2000000),
  NON_ADDITIVE_DIMENSION_ID DECIMAL(18,0),
  WINDOW_SPEC_JSON   VARCHAR(2000000),
  TYPE_PARAMS_JSON   VARCHAR(2000000),
  DEFINITION_SOURCE_ID DECIMAL(18,0),
  STATUS             VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

COMMENT ON TABLE SYS_SEMANTIC.METRICS (
  METRIC_TYPE IS 'Additive storage policy used by the compiler (SIMPLE, FILTERED, RATIO, DERIVED, WINDOW). Determines join and aggregation strategy.',
  METRIC_KIND IS 'Semantic classification for agents and discovery (SIMPLE, FILTERED, RATIO, DERIVED). Use this column for display and filtering.'
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.OBJECT_COLUMNS (
  OBJECT_ID          DECIMAL(18,0) NOT NULL,
  COLUMN_KIND        VARCHAR(32) NOT NULL,
  OBJECT_REF_ID      DECIMAL(18,0) NOT NULL,
  COLUMN_NAME        VARCHAR(256) NOT NULL,
  ORDINAL_POSITION   DECIMAL(18,0) NOT NULL,
  IS_VISIBLE         BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (OBJECT_ID, COLUMN_KIND, OBJECT_REF_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_DEPENDENCIES (
  METRIC_ID              DECIMAL(18,0) NOT NULL,
  DEPENDS_ON_OBJECT_TYPE VARCHAR(64) NOT NULL,
  DEPENDS_ON_OBJECT_ID   DECIMAL(18,0) NOT NULL,
  DEPENDENCY_KIND        VARCHAR(64) DEFAULT 'DIRECT' NOT NULL,
  PRIMARY KEY (METRIC_ID, DEPENDS_ON_OBJECT_TYPE, DEPENDS_ON_OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES (
  DEFINITION_SOURCE_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0),
  VERSION_ID           DECIMAL(18,0),
  SOURCE_KIND          VARCHAR(64) NOT NULL,
  SOURCE_NAME          VARCHAR(512),
  DEFINITION_SQL       VARCHAR(2000000) NOT NULL,
  NORMALIZED_JSON      VARCHAR(2000000),
  DEFINITION_HASH      VARCHAR(128),
  APPLY_STATUS         VARCHAR(64) DEFAULT 'APPLIED' NOT NULL,
  VALIDATION_RUN_ID    DECIMAL(18,0),
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_INPUTS (
  METRIC_ID            DECIMAL(18,0) NOT NULL,
  INPUT_ROLE           VARCHAR(64) NOT NULL,
  INPUT_OBJECT_TYPE    VARCHAR(64) NOT NULL,
  INPUT_OBJECT_ID      DECIMAL(18,0),
  EXPRESSION_ALIAS     VARCHAR(256),
  OFFSET_WINDOW        VARCHAR(512),
  FILTER_EXPR          VARCHAR(2000000),
  ORDINAL_POSITION     DECIMAL(18,0) NOT NULL,
  PRIMARY KEY (METRIC_ID, INPUT_ROLE, ORDINAL_POSITION)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_FILTERS (
  METRIC_ID            DECIMAL(18,0) NOT NULL,
  FILTER_KIND          VARCHAR(64) NOT NULL,
  FILTER_EXPR          VARCHAR(2000000) NOT NULL,
  RESOLVED_SQL_EXPR    VARCHAR(2000000),
  REQUIRED_DIMENSION_ID DECIMAL(18,0),
  REQUIRED_ENTITY_ID   DECIMAL(18,0),
  ORDINAL_POSITION     DECIMAL(18,0) DEFAULT 1 NOT NULL,
  PRIMARY KEY (METRIC_ID, FILTER_KIND, ORDINAL_POSITION)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.CALCULATION_GROUPS (
  CALCULATION_GROUP_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  GROUP_NAME           VARCHAR(256) NOT NULL,
  APPLIES_TO_METRIC_TYPE VARCHAR(64),
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.CALCULATION_ITEMS (
  CALCULATION_ITEM_ID  DECIMAL(18,0) IDENTITY PRIMARY KEY,
  CALCULATION_GROUP_ID DECIMAL(18,0) NOT NULL,
  ITEM_NAME            VARCHAR(256) NOT NULL,
  EXPRESSION_TEMPLATE  VARCHAR(2000000) NOT NULL,
  DISPLAY_ORDER        DECIMAL(18,0) DEFAULT 100,
  FORMAT_TEMPLATE      VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.SYNONYMS (
  SYNONYM_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID      DECIMAL(18,0) NOT NULL,
  VERSION_ID    DECIMAL(18,0) NOT NULL,
  OBJECT_TYPE   VARCHAR(64) NOT NULL,
  OBJECT_ID     DECIMAL(18,0) NOT NULL,
  SYNONYM       VARCHAR(512) NOT NULL,
  SYNONYM_SOURCE VARCHAR(64) DEFAULT 'MANUAL'
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_INSTRUCTIONS (
  INSTRUCTION_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0) NOT NULL,
  VERSION_ID           DECIMAL(18,0) NOT NULL,
  SCOPE_TYPE           VARCHAR(64) NOT NULL,
  SCOPE_ID             DECIMAL(18,0),
  INSTRUCTION_KIND     VARCHAR(64) NOT NULL,
  INSTRUCTION_TEXT     VARCHAR(2000000) NOT NULL,
  APPLIES_TO_ROLE      VARCHAR(256),
  PRIORITY             DECIMAL(18,0) DEFAULT 100,
  STATUS               VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.VERIFIED_QUERIES (
  VERIFIED_QUERY_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID                DECIMAL(18,0) NOT NULL,
  VERSION_ID              DECIMAL(18,0) NOT NULL,
  OBJECT_ID               DECIMAL(18,0),
  QUERY_NAME              VARCHAR(512) NOT NULL,
  NATURAL_LANGUAGE_TEXT   VARCHAR(2000000) NOT NULL,
  REQUEST_JSON            VARCHAR(2000000) NOT NULL,
  GENERATED_SQL           VARCHAR(2000000),
  EXPECTED_RESULT_SHAPE   VARCHAR(2000000),
  IS_ONBOARDING_EXAMPLE   BOOLEAN DEFAULT FALSE,
  VERIFIED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERIFIED_BY             VARCHAR(256) DEFAULT CURRENT_USER,
  STATUS                  VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_REQUEST_LOG (
  AGENT_REQUEST_ID      DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID              DECIMAL(18,0),
  VERSION_ID            DECIMAL(18,0),
  USER_NAME             VARCHAR(256) DEFAULT CURRENT_USER,
  CLIENT_NAME           VARCHAR(512),
  PURPOSE               VARCHAR(512),
  NATURAL_LANGUAGE_TEXT VARCHAR(2000000),
  REQUEST_JSON          VARCHAR(2000000),
  GENERATED_SQL         VARCHAR(2000000),
  PLAN_JSON             VARCHAR(2000000),
  STATUS                VARCHAR(64),
  ERROR_CODE            VARCHAR(128),
  ERROR_MESSAGE         VARCHAR(2000000),
  REQUESTED_METRICS     VARCHAR(2000000),
  REQUESTED_DIMENSIONS  VARCHAR(2000000),
  CACHE_HIT             BOOLEAN DEFAULT FALSE,
  STARTED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FINISHED_AT           TIMESTAMP,
  RUNTIME_MS            DECIMAL(18,0)
);

-- Server-side compile cache (BUG-D-002). The compiler is deterministic per
-- (model_version_id, normalized request), so a successful compile is reused
-- until PUBLISH_MODEL invalidates the entry. CACHE_KEY is an FNV-1a hex hash
-- computed in Lua over the canonical parsed request (sorted top-level keys,
-- client/purpose stripped). Entries are written best-effort: a transient
-- collision on insert (PK conflict from a concurrent identical compile) is
-- swallowed and the caller still sees the compile result.
CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.COMPILE_CACHE (
  MODEL_VERSION_ID  DECIMAL(18,0) NOT NULL,
  CACHE_KEY         VARCHAR(64)   NOT NULL,
  GENERATED_SQL     VARCHAR(2000000),
  PLAN_JSON         VARCHAR(2000000),
  VALIDATION_RUN_ID DECIMAL(18,0),
  CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_HIT_AT       TIMESTAMP,
  HIT_COUNT         DECIMAL(18,0) DEFAULT 0,
  PRIMARY KEY (MODEL_VERSION_ID, CACHE_KEY)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_FEEDBACK (
  FEEDBACK_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  AGENT_REQUEST_ID     DECIMAL(18,0),
  QUERY_LOG_ID         DECIMAL(18,0),
  FEEDBACK_KIND        VARCHAR(64) NOT NULL,
  VERDICT              VARCHAR(64) NOT NULL,
  COMMENT_TEXT         VARCHAR(2000000),
  PROPOSED_CHANGE_JSON VARCHAR(2000000),
  REVIEW_STATUS        VARCHAR(64) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  REVIEWED_AT          TIMESTAMP,
  REVIEWED_BY          VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.AGENT_SUGGESTIONS (
  SUGGESTION_ID        DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID             DECIMAL(18,0),
  VERSION_ID           DECIMAL(18,0),
  AGENT_REQUEST_ID     DECIMAL(18,0),
  QUERY_LOG_ID         DECIMAL(18,0),
  FEEDBACK_ID          DECIMAL(18,0),
  SUGGESTION_KIND      VARCHAR(64) NOT NULL,
  OBJECT_TYPE          VARCHAR(64),
  OBJECT_ID            DECIMAL(18,0),
  PROPOSED_CHANGE_JSON VARCHAR(2000000) NOT NULL,
  RATIONALE            VARCHAR(2000000),
  REVIEW_STATUS        VARCHAR(64) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY           VARCHAR(256) DEFAULT CURRENT_USER,
  REVIEWED_AT          TIMESTAMP,
  REVIEWED_BY          VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MATERIALIZATIONS (
  MATERIALIZATION_ID    DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID              DECIMAL(18,0) NOT NULL,
  VERSION_ID            DECIMAL(18,0) NOT NULL,
  MATERIALIZATION_NAME  VARCHAR(256) NOT NULL,
  PHYSICAL_SCHEMA       VARCHAR(256) NOT NULL,
  PHYSICAL_OBJECT       VARCHAR(256) NOT NULL,
  MATERIALIZATION_TYPE  VARCHAR(64) NOT NULL,
  FRESHNESS_POLICY      VARCHAR(512),
  STATUS                VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MATERIALIZATION_COLUMNS (
  MATERIALIZATION_ID DECIMAL(18,0) NOT NULL,
  OBJECT_TYPE        VARCHAR(64) NOT NULL,
  OBJECT_ID          DECIMAL(18,0) NOT NULL,
  PHYSICAL_COLUMN    VARCHAR(256) NOT NULL,
  ROLLUP_POLICY      VARCHAR(64),
  PRIMARY KEY (MATERIALIZATION_ID, OBJECT_TYPE, OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.OBJECT_PRIVILEGES (
  PRIVILEGE_ID  DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID      DECIMAL(18,0) NOT NULL,
  VERSION_ID    DECIMAL(18,0) NOT NULL,
  OBJECT_TYPE   VARCHAR(64) NOT NULL,
  OBJECT_ID     DECIMAL(18,0) NOT NULL,
  GRANTEE_TYPE  VARCHAR(64) NOT NULL,
  GRANTEE_NAME  VARCHAR(256) NOT NULL,
  PRIVILEGE     VARCHAR(64) NOT NULL,
  GRANTOR       VARCHAR(256),
  GRANTED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.QUERY_LOG (
  QUERY_LOG_ID          DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID              DECIMAL(18,0),
  VERSION_ID            DECIMAL(18,0),
  USER_NAME             VARCHAR(256) DEFAULT CURRENT_USER,
  CLIENT_NAME           VARCHAR(512),
  ORIGINAL_SQL          VARCHAR(2000000),
  GENERATED_SQL         VARCHAR(2000000),
  PLAN_JSON             VARCHAR(2000000),
  REQUESTED_DIMENSIONS  VARCHAR(2000000),
  REQUESTED_METRICS     VARCHAR(2000000),
  MATERIALIZATION_USED  VARCHAR(512),
  STATUS                VARCHAR(64),
  ERROR_CODE            VARCHAR(128),
  ERROR_MESSAGE         VARCHAR(2000000),
  STARTED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FINISHED_AT           TIMESTAMP,
  RUNTIME_MS            DECIMAL(18,0)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.VALIDATION_RUNS (
  VALIDATION_RUN_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID          DECIMAL(18,0),
  VERSION_ID        DECIMAL(18,0),
  MODEL_NAME        VARCHAR(256),
  STATUS            VARCHAR(32) DEFAULT 'RUNNING' NOT NULL,
  STARTED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FINISHED_AT       TIMESTAMP,
  ISSUE_COUNT       DECIMAL(18,0) DEFAULT 0 NOT NULL,
  ERROR_COUNT       DECIMAL(18,0) DEFAULT 0 NOT NULL,
  WARNING_COUNT     DECIMAL(18,0) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.VALIDATION_RESULTS (
  VALIDATION_RESULT_ID DECIMAL(18,0) IDENTITY PRIMARY KEY,
  VALIDATION_RUN_ID    DECIMAL(18,0) NOT NULL,
  MODEL_ID             DECIMAL(18,0),
  VERSION_ID           DECIMAL(18,0),
  SEVERITY             VARCHAR(32) NOT NULL,
  OBJECT_TYPE          VARCHAR(64) NOT NULL,
  OBJECT_NAME          VARCHAR(512),
  RULE_CODE            VARCHAR(128) NOT NULL,
  MESSAGE              VARCHAR(2000000) NOT NULL,
  CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.METRIC_DIMENSION_MATRIX (
  MODEL_ID          DECIMAL(18,0) NOT NULL,
  VERSION_ID        DECIMAL(18,0) NOT NULL,
  METRIC_ID         DECIMAL(18,0) NOT NULL,
  DIMENSION_ID      DECIMAL(18,0) NOT NULL,
  IS_VALID          BOOLEAN DEFAULT FALSE NOT NULL,
  REASON_CODE       VARCHAR(128) NOT NULL,
  RELATIONSHIP_PATH VARCHAR(2000000),
  VALIDATION_RUN_ID DECIMAL(18,0),
  UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (MODEL_ID, VERSION_ID, METRIC_ID, DIMENSION_ID)
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_PUBLISH_HISTORY (
  PUBLISH_ID       DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID         DECIMAL(18,0) NOT NULL,
  VERSION_ID       DECIMAL(18,0) NOT NULL,
  VERSION_NUMBER   DECIMAL(18,0) NOT NULL,
  PUBLISH_NUMBER   DECIMAL(18,0) NOT NULL,
  PUBLISHED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PUBLISHED_BY     VARCHAR(256) DEFAULT CURRENT_USER
);

CREATE TABLE IF NOT EXISTS SYS_SEMANTIC.MODEL_ROLE_GRANTS (
  GRANT_ID         DECIMAL(18,0) IDENTITY PRIMARY KEY,
  MODEL_ID         DECIMAL(18,0) NOT NULL,
  MODEL_NAME       VARCHAR(256) NOT NULL,
  ROLE_NAME        VARCHAR(256) NOT NULL,
  PUBLISHED_SCHEMA VARCHAR(256),
  GRANTED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  GRANTED_BY       VARCHAR(256) DEFAULT CURRENT_USER,
  STATUS           VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL
);
