-- SEMANTIC_SOURCE — the catalog, as the calling principal may see it.
--
-- Why this schema exists. The compiler runs as the caller: an Exasol scripting
-- script has the caller's rights, not the script owner's. So for a non-SYS
-- principal to compile anything at all, it needed SELECT on SYS_SEMANTIC — and
-- that is the whole catalog. Verified as a restricted analyst holding a grant on
-- exactly one model: every other model's metric definitions, every other user's
-- logged requests, and a map of the physical estate. A read surface that wide
-- cannot be narrowed by the compiler, because the caller can simply query the
-- tables without it.
--
-- So the surface itself is narrowed. SEMANTIC_SOURCE is one thin view per
-- SYS_SEMANTIC table the compiler reads, filtered to the models the caller is
-- authorized for. Callers are granted SELECT here and nowhere in SYS_SEMANTIC,
-- and a view is owner-rights, so the filter is enforced by the database rather
-- than by the compiler agreeing to apply it.
--
-- Thin is a contract, not a preference. SEMANTIC_CATALOG already has a view per
-- table, but those are denormalized for people — three to five joins each — and
-- load_catalog runs seventeen statements on a cold compile. These carry the
-- authorization filter and nothing else.
--
-- The generated block below is derived from the compiler's own Lua: every
-- `SEMANTIC_SOURCE.<TABLE>` it reads gets a view, so a new catalog read either
-- has one or fails the build. Regenerate with tools/package_lua_scripts.py.

-- Who the caller is, resolved once and read by everything that needs it.
--
-- ESV used to match principals as `IN (CURRENT_USER, 'PUBLIC')`, which misses
-- every inherited role: a user granted REGIONAL_ANALYST, which itself holds
-- SEMANTIC_READER, was not a SEMANTIC_READER as far as ESV was concerned.
-- Exasol answers this properly in EXA_SESSION_ROLES, which reports the
-- transitive closure; ESV simply did not ask.
CREATE OR REPLACE VIEW SEMANTIC_SOURCE.EFFECTIVE_PRINCIPAL AS
SELECT UPPER(CURRENT_USER) AS PRINCIPAL_NAME, 'USER' AS PRINCIPAL_KIND FROM DUAL
UNION ALL
SELECT UPPER(ROLE_NAME), 'ROLE' FROM EXA_SESSION_ROLES
UNION ALL
SELECT 'PUBLIC', 'PUBLIC' FROM DUAL;

-- Which models that principal may read.
--
-- Authorization is opt-in per model, and that is a deliberate default rather
-- than an oversight: a model nobody has granted stays visible to everyone, which
-- is exactly the behaviour every existing installation has today, so upgrading
-- changes nothing until someone calls GRANT_MODEL_ROLE. Granting the first role
-- is what turns the model private. The cost of that choice is worth stating
-- plainly: a newly created model is not private by default.
CREATE OR REPLACE VIEW SEMANTIC_SOURCE.AUTHORIZED_MODELS AS
SELECT m.MODEL_ID, m.MODEL_NAME, m.ACTIVE_VERSION_ID
FROM SYS_SEMANTIC.MODELS m
WHERE NOT EXISTS (
        SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
        WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
   OR EXISTS (
        SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
        JOIN SEMANTIC_SOURCE.EFFECTIVE_PRINCIPAL p
          ON p.PRINCIPAL_NAME = UPPER(g.ROLE_NAME)
        WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
   OR EXISTS (
        SELECT 1 FROM SEMANTIC_SOURCE.EFFECTIVE_PRINCIPAL p
        WHERE p.PRINCIPAL_NAME = UPPER(m.OWNER_ROLE))
   OR EXISTS (
        SELECT 1 FROM SEMANTIC_SOURCE.EFFECTIVE_PRINCIPAL p
        WHERE p.PRINCIPAL_NAME = 'DBA');

-- The baseline a caller needs, named once so a deployment does not have to
-- discover it by trial and error.
--
-- Note what is and is not in here. SELECT on SEMANTIC_SOURCE and EXECUTE on
-- SEMANTIC_ADMIN are the read and call surface. The three SYS_SEMANTIC tables
-- are the ones the compiler *writes* as the caller -- the compile cache and the
-- two logs -- and granting write on them is a real exposure, not a tidy-up: it
-- is what makes cache poisoning possible at all, which is why a cached
-- statement is checked against the model's declared relations before it is
-- served. Taking that write surface away from callers is its own piece of work;
-- until then this role states the exposure instead of hiding it.
--
-- Not included, deliberately: SELECT on the physical source schemas. Those are
-- the deployment's own data and the deployment's own grant to make -- and it is
-- where row-level security actually lives, so ESV handing it out would be ESV
-- deciding who sees which rows.
-- The role itself is created by tools/install.py: Exasol has no
-- `CREATE ROLE IF NOT EXISTS`, and this file re-runs on every install.
GRANT SELECT ON SCHEMA SEMANTIC_SOURCE TO SEMANTIC_USER;
GRANT SELECT ON SCHEMA SEMANTIC_CATALOG TO SEMANTIC_USER;
GRANT SELECT ON SCHEMA SEMANTIC_AGENT TO SEMANTIC_USER;
GRANT EXECUTE ON SCHEMA SEMANTIC_ADMIN TO SEMANTIC_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS_SEMANTIC.COMPILE_CACHE TO SEMANTIC_USER;
-- INSERT but not SELECT on the two logs. The compiler reads back only the row
-- it just wrote, and both reads already said WHERE USER_NAME = CURRENT_USER, so
-- the grant was simply wider than the need: SELECT here would have handed every
-- caller every other caller's logged questions.
GRANT INSERT ON SYS_SEMANTIC.AGENT_REQUEST_LOG TO SEMANTIC_USER;
GRANT INSERT ON SYS_SEMANTIC.QUERY_LOG TO SEMANTIC_USER;

-- A caller's own log rows, and only its own. These are scoped by user rather
-- than by model: a logged request belongs to whoever asked it.
CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MY_AGENT_REQUESTS AS
SELECT * FROM SYS_SEMANTIC.AGENT_REQUEST_LOG WHERE USER_NAME = CURRENT_USER;

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MY_QUERY_LOG AS
SELECT * FROM SYS_SEMANTIC.QUERY_LOG WHERE USER_NAME = CURRENT_USER;

-- BEGIN GENERATED SEMANTIC_SOURCE_VIEWS
CREATE OR REPLACE VIEW SEMANTIC_SOURCE.AGENT_INSTRUCTIONS AS
SELECT * FROM SYS_SEMANTIC.AGENT_INSTRUCTIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.ATTRIBUTE_BINDINGS AS
SELECT * FROM SYS_SEMANTIC.ATTRIBUTE_BINDINGS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.ATTRIBUTE_FUSION_POLICIES AS
SELECT * FROM SYS_SEMANTIC.ATTRIBUTE_FUSION_POLICIES
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.CUSTOM_EXTENSIONS AS
SELECT * FROM SYS_SEMANTIC.CUSTOM_EXTENSIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.DIMENSIONS AS
SELECT * FROM SYS_SEMANTIC.DIMENSIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.ENTITIES AS
SELECT * FROM SYS_SEMANTIC.ENTITIES
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.ENTITY_REPRESENTATIONS AS
SELECT * FROM SYS_SEMANTIC.ENTITY_REPRESENTATIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.FACTS AS
SELECT * FROM SYS_SEMANTIC.FACTS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.FROZEN_VIEWS AS
SELECT * FROM SYS_SEMANTIC.FROZEN_VIEWS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.IDENTITY_BINDINGS AS
SELECT * FROM SYS_SEMANTIC.IDENTITY_BINDINGS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.IDENTITY_MAPPING_RELATIONS AS
SELECT * FROM SYS_SEMANTIC.IDENTITY_MAPPING_RELATIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MATERIALIZATIONS AS
SELECT * FROM SYS_SEMANTIC.MATERIALIZATIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MATERIALIZATION_COLUMNS AS
SELECT * FROM SYS_SEMANTIC.MATERIALIZATION_COLUMNS
 WHERE MATERIALIZATION_ID IN (SELECT MATERIALIZATION_ID FROM SYS_SEMANTIC.MATERIALIZATIONS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.METRICS AS
SELECT * FROM SYS_SEMANTIC.METRICS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.METRIC_DEPENDENCIES AS
SELECT * FROM SYS_SEMANTIC.METRIC_DEPENDENCIES
 WHERE METRIC_ID IN (SELECT METRIC_ID FROM SYS_SEMANTIC.METRICS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.METRIC_DIMENSION_MATRIX AS
SELECT * FROM SYS_SEMANTIC.METRIC_DIMENSION_MATRIX
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.METRIC_FILTERS AS
SELECT * FROM SYS_SEMANTIC.METRIC_FILTERS
 WHERE METRIC_ID IN (SELECT METRIC_ID FROM SYS_SEMANTIC.METRICS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.METRIC_INPUTS AS
SELECT * FROM SYS_SEMANTIC.METRIC_INPUTS
 WHERE METRIC_ID IN (SELECT METRIC_ID FROM SYS_SEMANTIC.METRICS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODELS AS
SELECT * FROM SYS_SEMANTIC.MODELS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODEL_EVOLUTION_REVIEWS AS
SELECT * FROM SYS_SEMANTIC.MODEL_EVOLUTION_REVIEWS
 WHERE SUGGESTION_ID IN (SELECT SUGGESTION_ID FROM SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODEL_EVOLUTION_SUGGESTIONS AS
SELECT * FROM SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODEL_EVOLUTION_TARGETS AS
SELECT * FROM SYS_SEMANTIC.MODEL_EVOLUTION_TARGETS
 WHERE SUGGESTION_ID IN (SELECT SUGGESTION_ID FROM SYS_SEMANTIC.MODEL_EVOLUTION_SUGGESTIONS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODEL_ROLE_GRANTS AS
SELECT * FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODEL_VERSIONS AS
SELECT * FROM SYS_SEMANTIC.MODEL_VERSIONS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.OBJECT_COLUMNS AS
SELECT * FROM SYS_SEMANTIC.OBJECT_COLUMNS
 WHERE OBJECT_ID IN (SELECT OBJECT_ID FROM SYS_SEMANTIC.SEMANTIC_OBJECTS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.RELATIONSHIPS AS
SELECT * FROM SYS_SEMANTIC.RELATIONSHIPS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.RELATIONSHIP_KEY_MAPPINGS AS
SELECT * FROM SYS_SEMANTIC.RELATIONSHIP_KEY_MAPPINGS
 WHERE RELATIONSHIP_ID IN (SELECT RELATIONSHIP_ID FROM SYS_SEMANTIC.RELATIONSHIPS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.REPRESENTATION_AUTHORITIES AS
SELECT * FROM SYS_SEMANTIC.REPRESENTATION_AUTHORITIES
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.SEMANTIC_DEFINITION_SOURCES AS
SELECT * FROM SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.SEMANTIC_IDENTITIES AS
SELECT * FROM SYS_SEMANTIC.SEMANTIC_IDENTITIES
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.SEMANTIC_OBJECTS AS
SELECT * FROM SYS_SEMANTIC.SEMANTIC_OBJECTS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.SOURCE_TRUST AS
SELECT * FROM SYS_SEMANTIC.SOURCE_TRUST
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.SYNONYMS AS
SELECT * FROM SYS_SEMANTIC.SYNONYMS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.UNIQUE_KEYS AS
SELECT * FROM SYS_SEMANTIC.UNIQUE_KEYS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.UNIQUE_KEY_COLUMNS AS
SELECT * FROM SYS_SEMANTIC.UNIQUE_KEY_COLUMNS
 WHERE UNIQUE_KEY_ID IN (SELECT UNIQUE_KEY_ID FROM SYS_SEMANTIC.UNIQUE_KEYS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.VALIDATION_RESULTS AS
SELECT * FROM SYS_SEMANTIC.VALIDATION_RESULTS
 WHERE VALIDATION_RUN_ID IN (SELECT VALIDATION_RUN_ID FROM SYS_SEMANTIC.VALIDATION_RUNS
                  WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA')));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.VALIDATION_RUNS AS
SELECT * FROM SYS_SEMANTIC.VALIDATION_RUNS
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

CREATE OR REPLACE VIEW SEMANTIC_SOURCE.VERIFIED_QUERIES AS
SELECT * FROM SYS_SEMANTIC.VERIFIED_QUERIES
 WHERE MODEL_ID IN (SELECT m.MODEL_ID FROM SYS_SEMANTIC.MODELS m
       WHERE NOT EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                          WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE')
          OR UPPER(m.OWNER_ROLE) = UPPER(CURRENT_USER)
          OR UPPER(m.OWNER_ROLE) IN (SELECT UPPER(ROLE_NAME) FROM EXA_SESSION_ROLES)
          OR EXISTS (SELECT 1 FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
                      WHERE g.MODEL_ID = m.MODEL_ID AND g.STATUS = 'ACTIVE'
                        AND (UPPER(g.ROLE_NAME) = UPPER(CURRENT_USER)
                             OR UPPER(g.ROLE_NAME) = 'PUBLIC'
                             OR UPPER(g.ROLE_NAME) IN (SELECT UPPER(ROLE_NAME)
                                                         FROM EXA_SESSION_ROLES)))
          OR EXISTS (SELECT 1 FROM EXA_SESSION_ROLES WHERE ROLE_NAME = 'DBA'));

-- Every physical relation this model's compiled SQL may read, in one view.
--
-- The compile cache checks a cached statement against this set before serving
-- it (see compile_cache.trust_boundary). That check runs on every cache hit, so
-- it reads one view carrying the authorization filter once rather than three
-- tables carrying it three times.
--
-- The three sources are the declarations a planner can turn into a FROM clause:
-- an entity's representation, a materialization substituted for one, and an F5
-- identity mapping relation joined into one. It is created after the views it
-- reads, which is why it lives at the end of the generated block.
CREATE OR REPLACE VIEW SEMANTIC_SOURCE.MODEL_RELATIONS AS
SELECT VERSION_ID, 'REPRESENTATION' AS RELATION_KIND,
       SOURCE_SCHEMA AS RELATION_SCHEMA, SOURCE_OBJECT AS RELATION_OBJECT
  FROM SEMANTIC_SOURCE.ENTITY_REPRESENTATIONS WHERE STATUS = 'ACTIVE'
UNION ALL
SELECT VERSION_ID, 'MATERIALIZATION', PHYSICAL_SCHEMA, PHYSICAL_OBJECT
  FROM SEMANTIC_SOURCE.MATERIALIZATIONS WHERE STATUS = 'ACTIVE'
UNION ALL
SELECT VERSION_ID, 'IDENTITY_MAPPING', SOURCE_SCHEMA, SOURCE_OBJECT
  FROM SEMANTIC_SOURCE.IDENTITY_MAPPING_RELATIONS WHERE STATUS = 'ACTIVE';
-- END GENERATED SEMANTIC_SOURCE_VIEWS








-- SEMANTIC_CATALOG.GOVERNANCE_FOR_MODEL is created here, not with the other
-- catalog views in 002, because it reads SEMANTIC_SOURCE.AUTHORIZED_MODELS and
-- 002 runs before this file exists. Putting it in 002 installed fine over an
-- existing deployment and failed on every clean install, which is the kind of
-- ordering fault only a full reset finds.
--
-- What this model promises, what it can vouch for, and where it stops.
--
-- One row per model, and one surface rather than two: the governance state and
-- the capability state are the same question asked twice -- "can I rely on this
-- number" -- and answering them in separate views would let them disagree.
-- Everything here is derived from what the other surfaces already hold, so
-- nothing is declared twice.
--
-- SUMMARY is the sentence. An operator who reads nothing else should still learn
-- whether the model is enforcing anything, whether anything is unvouched for,
-- and whether a frozen view is carrying an old answer.
-- Which SQL shapes this layer accepts, and what it says when it does not.
--
-- A tool integrator should not discover the boundary by hitting it. This is the
-- companion to GOVERNANCE_FOR_MODEL below and deliberately the same kind of
-- answer: that view says what the layer vouches for, this one says what it
-- accepts, and between them "can I rely on this number" has one place to go.
--
-- Declared rather than derived, because there is nothing to derive it from --
-- the shapes live in a parser. The refusal codes are the check: each one is a
-- code the compiler actually emits, and tests/test_conventions.py already
-- forbids a code from meaning two things, so a row naming a code that has gone
-- away is visible.
CREATE OR REPLACE VIEW SEMANTIC_CATALOG.QUERY_CAPABILITIES AS
SELECT * FROM (VALUES
  ('SELECT over a published object', 'SUPPORTED',
   'Semantic field names, SELECT *, and MEASURE(metric) / agg(metric).', NULL, NULL),
  ('WHERE on dimensions', 'SUPPORTED',
   '=, !=, <>, <, <=, >, >=, LIKE, IN, BETWEEN, IS NULL, IS NOT NULL. Text comparisons are case-insensitive.', NULL, NULL),
  ('HAVING on metrics', 'SUPPORTED',
   'A metric predicate written in WHERE is routed to HAVING during parsing. HAVING without a metric to group by is refused.', 'SEMANTIC_QUERY_026', NULL),
  ('GROUP BY', 'SUPPORTED',
   'Optional. Inferred from the selected dimensions when omitted; an explicit list must cover them exactly.', 'SEMANTIC_QUERY_008', NULL),
  ('ORDER BY and LIMIT', 'SUPPORTED',
   'Selected output fields, output aliases, or ordinals. LIMIT 0 returns the shape with no rows.', NULL, NULL),
  ('ORDER BY a field that is not selected', 'SUPPORTED',
   'Also OFFSET, SELECT DISTINCT, arithmetic and CASE in the select list, IN (subquery) and correlated EXISTS on a selected dimension.', NULL, NULL),
  ('Statements that wrap the object', 'SUPPORTED',
   'Subquery, CTE, union, window, TopN wrapper, CAST, arithmetic and COUNT(*) around a reference, by expanding the reference into a derived table.', NULL, NULL),
  ('The shape of the statement around the object', 'DOES NOT MATTER',
   'A construct is accepted or refused the same way whether the object is referenced bare or wrapped in a subquery. Wrapping a statement is never a workaround for a refusal.', NULL, NULL),
  ('CREATE VIEW over an object', 'SUPPORTED',
   'The stored text is compiled SQL, so the view answers with no preprocessor. Recorded in SEMANTIC_CATALOG.FROZEN_VIEWS and checked by CHECK_FROZEN_VIEWS.', NULL, NULL),
  ('Joining an object to another relation', 'REFUSED BY DEFAULT',
   'The join can repeat the semantic result''s rows and re-aggregation then double-counts. Opt in per model with SET_MODEL_DERIVED_COMPOSITION.', 'SEMANTIC_QUERY_012', NULL),
  ('Grouping the object where the layer cannot read the statement', 'REFUSED BY DEFAULT',
   'The object is already aggregated to the grain its fields imply, so GROUP BY or HAVING beside the reference groups a grouped result. Where the statement is one the whole-statement path reads, it says something sharper -- see the GROUP BY, HAVING and COUNT(*) rows. Opt in with SET_MODEL_DERIVED_COMPOSITION.', 'SEMANTIC_QUERY_015', NULL),
  ('Selecting a field the model withholds', 'REFUSED',
   'IS_PRIVATE on a metric or IS_HIDDEN on a dimension removes the field from discovery and from queries, filters included.', 'SEMANTIC_QUERY_027', 'SEMANTIC_REQUEST_027'),
  ('Selecting a masked field', 'REFUSED',
   'DISPLAY_POLICY = ''MASK'' withholds the value from results. Filtering on it still works.', 'SEMANTIC_QUERY_024', 'SEMANTIC_REQUEST_024'),
  ('Naming a field the object does not publish', 'REFUSED',
   'The refusal names the field and, where one is close enough to suggest, what it might have meant.', 'SEMANTIC_QUERY_020', 'SEMANTIC_REQUEST_020'),
  ('Filtering on a dimension the statement does not select', 'SUPPORTED',
   'The filter is applied before aggregation, as it is on a bare statement, however the object is wrapped. Where it cannot be -- it contains a subquery the compile does not support, reads another semantic object, or sits beside a join -- the statement is refused rather than grouped by the filtered dimension. Filter with literal values, or select the dimension.', 'SEMANTIC_QUERY_017', NULL),
  ('An outer SUM or AVG over a metric that does not add up', 'REFUSED',
   'Aggregating the object in an outer block is supported. For a metric that does not add up across groups -- an average, a ratio, a distinct count -- a sum or average of its per-group values is not the metric at any grain, so it is refused unless the outer block groups by every dimension the subquery is compiled at. MIN, MAX and COUNT are accepted. Opt in with SET_MODEL_DERIVED_COMPOSITION.', 'SEMANTIC_QUERY_016', NULL),
  ('An aggregate the metric does not declare', 'REFUSED',
   'MEASURE() and agg() may only wrap a metric, and only with the aggregate that metric declares.', 'SEMANTIC_QUERY_007', NULL),
  ('A SELECT list that names no field', 'REFUSED',
   'SELECT supports semantic field names, MEASURE(metric), or *.', 'SEMANTIC_QUERY_005', NULL),
  ('A wrapper naming no column of the object', 'REFUSED',
   'Which columns to compile cannot be inferred, and defaulting to all of them would change the grain silently.', 'SEMANTIC_QUERY_011', NULL),
  ('COUNT(*) over a semantic object', 'REFUSED',
   'Its answer depends on a grain the caller never named. Wrap the object in a subquery and count that.', 'SEMANTIC_QUERY_010', NULL),
  ('Reading a relation the model does not vouch for', 'REFUSED',
   'In GOVERNED mode every representation must resolve through a relation that can carry row and column policy.', 'SEMANTIC_QUERY_028', 'SEMANTIC_REQUEST_028'),
  ('Malformed or non-Exasol SQL around the object', 'REPORTED BY THE DATABASE',
   'A statement the layer rewrote but Exasol then rejects -- a syntax error, DISTINCT ON, LIMIT -1 -- comes back with Exasol''s own message naming the problem, not a rule code. The line it reports is a line of your statement; the column counts the rewritten text, so read the line and ignore the column.', NULL, NULL)
) AS t (SHAPE, SUPPORT, DETAIL, SQL_REFUSAL_CODE, REQUEST_REFUSAL_CODE);

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.GOVERNANCE_FOR_MODEL AS
WITH trust AS (
  SELECT MODEL_ID,
         COUNT(CASE WHEN TRUST_CLASS = 'GOVERNED' THEN 1 END) AS GOVERNED_SOURCES,
         COUNT(CASE WHEN TRUST_CLASS = 'RAW' THEN 1 END) AS RAW_SOURCES,
         COUNT(CASE WHEN TRUST_CLASS = 'DIVERGENT' THEN 1 END) AS DIVERGENT_SOURCES,
         COUNT(CASE WHEN TRUST_CLASS = 'UNKNOWN' THEN 1 END) AS UNKNOWN_SOURCES,
         MAX(DERIVED_AT) AS TRUST_DERIVED_AT
    FROM SYS_SEMANTIC.SOURCE_TRUST
   GROUP BY MODEL_ID
),
frozen AS (
  SELECT fv.MODEL_ID, COUNT(*) AS FROZEN_VIEWS
    FROM SYS_SEMANTIC.FROZEN_VIEWS fv
    JOIN SYS.EXA_ALL_VIEWS v
      ON UPPER(v.VIEW_SCHEMA) = UPPER(fv.VIEW_SCHEMA)
     AND UPPER(v.VIEW_NAME) = UPPER(fv.VIEW_NAME)
   GROUP BY fv.MODEL_ID
)
SELECT
  m.MODEL_NAME,
  m.GOVERNANCE_MODE,
  m.ALLOW_DERIVED_COMPOSITION,
  CASE WHEN a.MODEL_ID IS NULL THEN FALSE ELSE TRUE END AS VISIBLE_TO_CALLER,
  COALESCE(t.GOVERNED_SOURCES, 0) AS GOVERNED_SOURCES,
  COALESCE(t.RAW_SOURCES, 0) AS RAW_SOURCES,
  COALESCE(t.DIVERGENT_SOURCES, 0) AS DIVERGENT_SOURCES,
  COALESCE(t.UNKNOWN_SOURCES, 0) AS UNKNOWN_SOURCES,
  COALESCE(f.FROZEN_VIEWS, 0) AS FROZEN_VIEWS,
  t.TRUST_DERIVED_AT,
  CASE
    WHEN t.MODEL_ID IS NULL THEN
      'Not classified. VALIDATE_MODEL derives which sources this model can vouch'
      || ' for, and has not run since the last change that could affect them.'
    WHEN UPPER(m.GOVERNANCE_MODE) = 'GOVERNED' THEN
      'Governed: every representation must resolve through a view that can carry'
      || ' row and column policy, and ' || COALESCE(t.GOVERNED_SOURCES, 0)
      || ' of ' || (COALESCE(t.GOVERNED_SOURCES,0) + COALESCE(t.RAW_SOURCES,0)
                    + COALESCE(t.DIVERGENT_SOURCES,0) + COALESCE(t.UNKNOWN_SOURCES,0))
      || ' sources do. '
      || CASE WHEN COALESCE(t.DIVERGENT_SOURCES,0) + COALESCE(t.UNKNOWN_SOURCES,0) > 0
              THEN 'It will refuse to compile or to freeze a view until the '
                   || (COALESCE(t.DIVERGENT_SOURCES,0) + COALESCE(t.UNKNOWN_SOURCES,0))
                   || ' it cannot vouch for are rebuilt or retired.'
              ELSE 'Nothing is unvouched for.' END
    ELSE
      'Open: the layer reports on its sources but enforces nothing about them. '
      || COALESCE(t.RAW_SOURCES, 0) || ' read base tables directly'
      || CASE WHEN COALESCE(t.DIVERGENT_SOURCES,0) > 0
              THEN ' and ' || t.DIVERGENT_SOURCES
                   || ' substitute for a representation without carrying its policy'
              ELSE '' END
      || '. Row and column policy has to live in the sources themselves.'
  END
  || CASE WHEN COALESCE(f.FROZEN_VIEWS, 0) > 0
          THEN ' ' || f.FROZEN_VIEWS || ' database view(s) hold SQL compiled from this'
               || ' model and keep answering with it; CHECK_FROZEN_VIEWS says whether'
               || ' they still match.'
          ELSE '' END
  || CASE WHEN m.ALLOW_DERIVED_COMPOSITION
          THEN ' Composition is allowed: a published object may be joined to another'
               || ' relation, which the layer does not supervise.'
          ELSE '' END AS SUMMARY
FROM SYS_SEMANTIC.MODELS m
LEFT JOIN trust t ON t.MODEL_ID = m.MODEL_ID
LEFT JOIN frozen f ON f.MODEL_ID = m.MODEL_ID
LEFT JOIN SEMANTIC_SOURCE.AUTHORIZED_MODELS a ON a.MODEL_ID = m.MODEL_ID;
