CREATE OR REPLACE VIEW SEMANTIC_CATALOG.MODELS AS
SELECT
  m.MODEL_ID,
  m.MODEL_NAME,
  m.PUBLISHED_SCHEMA,
  m.DESCRIPTION,
  m.OWNER_ROLE,
  m.STATUS,
  m.ACTIVE_VERSION_ID,
  mv.VERSION_NUMBER AS ACTIVE_VERSION_NUMBER,
  m.SURFACE_TYPE,
  m.CREATED_AT,
  m.CREATED_BY,
  m.UPDATED_AT,
  m.UPDATED_BY
FROM SYS_SEMANTIC.MODELS m
LEFT JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = m.ACTIVE_VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.MODEL_VERSIONS AS
SELECT
  mv.VERSION_ID,
  mv.MODEL_ID,
  m.MODEL_NAME,
  mv.VERSION_NUMBER,
  mv.VERSION_LABEL,
  mv.STATUS,
  mv.CHANGE_SUMMARY,
  mv.CATALOG_HASH,
  mv.CREATED_AT,
  mv.CREATED_BY
FROM SYS_SEMANTIC.MODEL_VERSIONS mv
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mv.MODEL_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.ENTITIES AS
SELECT
  e.ENTITY_ID,
  e.MODEL_ID,
  m.MODEL_NAME,
  e.VERSION_ID,
  mv.VERSION_NUMBER,
  e.ENTITY_NAME,
  e.SOURCE_SCHEMA,
  e.SOURCE_OBJECT,
  e.SOURCE_ALIAS,
  e.PRIMARY_KEY_EXPR,
  e.GRAIN_DESCRIPTION,
  e.DESCRIPTION,
  e.STATUS
FROM SYS_SEMANTIC.ENTITIES e
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = e.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = e.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.SEMANTIC_OBJECTS AS
SELECT
  so.OBJECT_ID,
  so.MODEL_ID,
  m.MODEL_NAME,
  so.VERSION_ID,
  mv.VERSION_NUMBER,
  so.OBJECT_NAME,
  re.ENTITY_NAME AS ROOT_ENTITY_NAME,
  so.DESCRIPTION,
  so.STATUS
FROM SYS_SEMANTIC.SEMANTIC_OBJECTS so
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = so.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = so.VERSION_ID
LEFT JOIN SYS_SEMANTIC.ENTITIES re
  ON re.ENTITY_ID = so.ROOT_ENTITY_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.RELATIONSHIPS AS
SELECT
  r.RELATIONSHIP_ID,
  r.MODEL_ID,
  m.MODEL_NAME,
  r.VERSION_ID,
  mv.VERSION_NUMBER,
  r.RELATIONSHIP_NAME,
  fe.ENTITY_NAME AS FROM_ENTITY_NAME,
  te.ENTITY_NAME AS TO_ENTITY_NAME,
  r.JOIN_CONDITION,
  r.RELATIONSHIP_CARDINALITY,
  r.JOIN_TYPE,
  r.IS_REQUIRED,
  r.FANOUT_POLICY,
  r.PATH_PRIORITY,
  r.DESCRIPTION,
  r.STATUS
FROM SYS_SEMANTIC.RELATIONSHIPS r
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = r.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = r.VERSION_ID
JOIN SYS_SEMANTIC.ENTITIES fe
  ON fe.ENTITY_ID = r.FROM_ENTITY_ID
JOIN SYS_SEMANTIC.ENTITIES te
  ON te.ENTITY_ID = r.TO_ENTITY_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.DIMENSIONS AS
SELECT
  d.DIMENSION_ID,
  d.MODEL_ID,
  m.MODEL_NAME,
  d.VERSION_ID,
  mv.VERSION_NUMBER,
  e.ENTITY_NAME,
  d.DIMENSION_NAME,
  d.EXPRESSION,
  d.DATA_TYPE,
  d.DISPLAY_NAME,
  d.DESCRIPTION,
  d.FORMAT_HINT,
  d.UNIT_HINT,
  d.SENSITIVITY_LABEL,
  d.DISPLAY_POLICY,
  d.IS_HIDDEN,
  d.IS_CERTIFIED,
  d.STATUS
FROM SYS_SEMANTIC.DIMENSIONS d
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = d.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = d.VERSION_ID
JOIN SYS_SEMANTIC.ENTITIES e
  ON e.ENTITY_ID = d.ENTITY_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.FACTS AS
SELECT
  f.FACT_ID,
  f.MODEL_ID,
  m.MODEL_NAME,
  f.VERSION_ID,
  mv.VERSION_NUMBER,
  e.ENTITY_NAME,
  f.FACT_NAME,
  f.EXPRESSION,
  f.DATA_TYPE,
  f.ADDITIVE_POLICY,
  f.DISPLAY_NAME,
  f.DESCRIPTION,
  f.FORMAT_HINT,
  f.UNIT_HINT,
  f.SENSITIVITY_LABEL,
  f.DISPLAY_POLICY,
  f.IS_PRIVATE,
  f.IS_CERTIFIED,
  f.STATUS
FROM SYS_SEMANTIC.FACTS f
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = f.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = f.VERSION_ID
JOIN SYS_SEMANTIC.ENTITIES e
  ON e.ENTITY_ID = f.ENTITY_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRICS AS
SELECT
  mt.METRIC_ID,
  mt.MODEL_ID,
  m.MODEL_NAME,
  mt.VERSION_ID,
  mv.VERSION_NUMBER,
  be.ENTITY_NAME AS BASE_ENTITY_NAME,
  mt.METRIC_NAME,
  mt.EXPRESSION,
  mt.FILTER_EXPR,
  mt.METRIC_TYPE,
  mt.DATA_TYPE,
  mt.DISPLAY_NAME,
  mt.DESCRIPTION,
  mt.FORMAT_HINT,
  mt.UNIT_HINT,
  mt.SENSITIVITY_LABEL,
  mt.DISPLAY_POLICY,
  mt.IS_PRIVATE,
  mt.IS_CERTIFIED,
  mt.OWNER_ROLE,
  mt.METRIC_KIND,
  mt.AGGREGATION_FUNCTION,
  mt.MEASURE_EXPR,
  mt.SEMANTIC_FILTER_EXPR,
  mt.SQL_FILTER_EXPR,
  mt.DISTINCT_KEY_EXPR,
  mt.NON_ADDITIVE_DIMENSION_ID,
  nad.DIMENSION_NAME AS NON_ADDITIVE_DIMENSION_NAME,
  mt.WINDOW_SPEC_JSON,
  mt.TYPE_PARAMS_JSON,
  mt.DEFINITION_SOURCE_ID,
  mt.STATUS
FROM SYS_SEMANTIC.METRICS mt
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mt.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mt.VERSION_ID
LEFT JOIN SYS_SEMANTIC.ENTITIES be
  ON be.ENTITY_ID = mt.BASE_ENTITY_ID
LEFT JOIN SYS_SEMANTIC.DIMENSIONS nad
  ON nad.DIMENSION_ID = mt.NON_ADDITIVE_DIMENSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.OBJECT_COLUMNS AS
SELECT
  oc.OBJECT_ID,
  so.OBJECT_NAME,
  m.MODEL_NAME,
  mv.VERSION_NUMBER,
  oc.COLUMN_KIND,
  oc.OBJECT_REF_ID,
  oc.COLUMN_NAME,
  oc.ORDINAL_POSITION,
  oc.IS_VISIBLE,
  COALESCE(d.DISPLAY_NAME, f.DISPLAY_NAME, mt.DISPLAY_NAME) AS DISPLAY_NAME,
  COALESCE(d.DESCRIPTION, f.DESCRIPTION, mt.DESCRIPTION) AS DESCRIPTION,
  COALESCE(d.DATA_TYPE, f.DATA_TYPE, mt.DATA_TYPE) AS DATA_TYPE,
  COALESCE(d.FORMAT_HINT, f.FORMAT_HINT, mt.FORMAT_HINT) AS FORMAT_HINT,
  COALESCE(d.UNIT_HINT, f.UNIT_HINT, mt.UNIT_HINT) AS UNIT_HINT
FROM SYS_SEMANTIC.OBJECT_COLUMNS oc
JOIN SYS_SEMANTIC.SEMANTIC_OBJECTS so
  ON so.OBJECT_ID = oc.OBJECT_ID
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = so.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = so.VERSION_ID
LEFT JOIN SYS_SEMANTIC.DIMENSIONS d
  ON oc.COLUMN_KIND = 'DIMENSION'
 AND d.DIMENSION_ID = oc.OBJECT_REF_ID
LEFT JOIN SYS_SEMANTIC.FACTS f
  ON oc.COLUMN_KIND = 'FACT'
 AND f.FACT_ID = oc.OBJECT_REF_ID
LEFT JOIN SYS_SEMANTIC.METRICS mt
  ON oc.COLUMN_KIND = 'METRIC'
 AND mt.METRIC_ID = oc.OBJECT_REF_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.SYNONYMS AS
SELECT
  s.SYNONYM_ID,
  s.MODEL_ID,
  m.MODEL_NAME,
  s.VERSION_ID,
  mv.VERSION_NUMBER,
  s.OBJECT_TYPE,
  s.OBJECT_ID,
  s.SYNONYM,
  s.SYNONYM_SOURCE
FROM SYS_SEMANTIC.SYNONYMS s
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = s.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = s.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.MATERIALIZATIONS AS
SELECT
  mat.MATERIALIZATION_ID,
  mat.MODEL_ID,
  m.MODEL_NAME,
  mat.VERSION_ID,
  mv.VERSION_NUMBER,
  mat.MATERIALIZATION_NAME,
  mat.PHYSICAL_SCHEMA,
  mat.PHYSICAL_OBJECT,
  mat.MATERIALIZATION_TYPE,
  mat.FRESHNESS_POLICY,
  mat.STATUS
FROM SYS_SEMANTIC.MATERIALIZATIONS mat
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mat.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mat.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.MATERIALIZATION_COLUMNS AS
SELECT
  mc.MATERIALIZATION_ID,
  mat.MATERIALIZATION_NAME,
  mat.MODEL_ID,
  m.MODEL_NAME,
  mat.VERSION_ID,
  mv.VERSION_NUMBER,
  mc.OBJECT_TYPE,
  mc.OBJECT_ID,
  COALESCE(d.DIMENSION_NAME, mt.METRIC_NAME) AS OBJECT_NAME,
  mc.PHYSICAL_COLUMN,
  mc.ROLLUP_POLICY
FROM SYS_SEMANTIC.MATERIALIZATION_COLUMNS mc
JOIN SYS_SEMANTIC.MATERIALIZATIONS mat
  ON mat.MATERIALIZATION_ID = mc.MATERIALIZATION_ID
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mat.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mat.VERSION_ID
LEFT JOIN SYS_SEMANTIC.DIMENSIONS d
  ON mc.OBJECT_TYPE = 'DIMENSION'
 AND d.DIMENSION_ID = mc.OBJECT_ID
LEFT JOIN SYS_SEMANTIC.METRICS mt
  ON mc.OBJECT_TYPE = 'METRIC'
 AND mt.METRIC_ID = mc.OBJECT_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.AGENT_INSTRUCTIONS AS
SELECT
  ai.INSTRUCTION_ID,
  ai.MODEL_ID,
  m.MODEL_NAME,
  ai.VERSION_ID,
  mv.VERSION_NUMBER,
  ai.SCOPE_TYPE,
  ai.SCOPE_ID,
  ai.INSTRUCTION_KIND,
  ai.INSTRUCTION_TEXT,
  ai.APPLIES_TO_ROLE,
  ai.PRIORITY,
  ai.STATUS,
  ai.CREATED_AT,
  ai.CREATED_BY
FROM SYS_SEMANTIC.AGENT_INSTRUCTIONS ai
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = ai.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = ai.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.VERIFIED_QUERIES AS
SELECT
  vq.VERIFIED_QUERY_ID,
  vq.MODEL_ID,
  m.MODEL_NAME,
  vq.VERSION_ID,
  mv.VERSION_NUMBER,
  so.OBJECT_NAME,
  vq.QUERY_NAME,
  vq.NATURAL_LANGUAGE_TEXT,
  vq.REQUEST_JSON,
  vq.GENERATED_SQL,
  vq.EXPECTED_RESULT_SHAPE,
  vq.IS_ONBOARDING_EXAMPLE,
  vq.VERIFIED_AT,
  vq.VERIFIED_BY,
  vq.STATUS
FROM SYS_SEMANTIC.VERIFIED_QUERIES vq
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = vq.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = vq.VERSION_ID
LEFT JOIN SYS_SEMANTIC.SEMANTIC_OBJECTS so
  ON so.OBJECT_ID = vq.OBJECT_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.VALIDATION_RUNS AS
SELECT
  vr.VALIDATION_RUN_ID,
  vr.MODEL_ID,
  m.MODEL_NAME,
  vr.VERSION_ID,
  mv.VERSION_NUMBER,
  vr.STATUS,
  vr.STARTED_AT,
  vr.FINISHED_AT,
  vr.ISSUE_COUNT,
  vr.ERROR_COUNT,
  vr.WARNING_COUNT
FROM SYS_SEMANTIC.VALIDATION_RUNS vr
LEFT JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = vr.MODEL_ID
LEFT JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = vr.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.VALIDATION_RESULTS AS
SELECT
  res.VALIDATION_RESULT_ID,
  res.VALIDATION_RUN_ID,
  res.MODEL_ID,
  m.MODEL_NAME,
  res.VERSION_ID,
  mv.VERSION_NUMBER,
  res.SEVERITY,
  res.OBJECT_TYPE,
  res.OBJECT_NAME,
  res.RULE_CODE,
  res.MESSAGE,
  res.CREATED_AT
FROM SYS_SEMANTIC.VALIDATION_RESULTS res
LEFT JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = res.MODEL_ID
LEFT JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = res.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.CURRENT_VALIDATION_ISSUES AS
SELECT
  res.VALIDATION_RESULT_ID,
  res.VALIDATION_RUN_ID,
  res.MODEL_ID,
  m.MODEL_NAME,
  res.VERSION_ID,
  mv.VERSION_NUMBER,
  vr.STATUS AS VALIDATION_STATUS,
  res.SEVERITY,
  res.OBJECT_TYPE,
  res.OBJECT_NAME,
  res.RULE_CODE,
  res.MESSAGE,
  res.CREATED_AT
FROM SYS_SEMANTIC.VALIDATION_RESULTS res
JOIN SYS_SEMANTIC.VALIDATION_RUNS vr
  ON vr.VALIDATION_RUN_ID = res.VALIDATION_RUN_ID
LEFT JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = res.MODEL_ID
LEFT JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = res.VERSION_ID
WHERE res.VALIDATION_RUN_ID = (
  SELECT MAX(vr2.VALIDATION_RUN_ID)
  FROM SYS_SEMANTIC.VALIDATION_RUNS vr2
  WHERE vr2.MODEL_ID = res.MODEL_ID
    AND vr2.VERSION_ID = res.VERSION_ID
);

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_DIMENSION_MATRIX AS
SELECT
  mdm.MODEL_ID,
  m.MODEL_NAME,
  mdm.VERSION_ID,
  mv.VERSION_NUMBER,
  mdm.METRIC_ID,
  mt.METRIC_NAME,
  mdm.DIMENSION_ID,
  d.DIMENSION_NAME,
  mdm.IS_VALID,
  mdm.REASON_CODE,
  mdm.RELATIONSHIP_PATH,
  mdm.VALIDATION_RUN_ID,
  mdm.UPDATED_AT
FROM SYS_SEMANTIC.METRIC_DIMENSION_MATRIX mdm
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mdm.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mdm.VERSION_ID
JOIN SYS_SEMANTIC.METRICS mt
  ON mt.METRIC_ID = mdm.METRIC_ID
JOIN SYS_SEMANTIC.DIMENSIONS d
  ON d.DIMENSION_ID = mdm.DIMENSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.SEMANTIC_DEFINITION_SOURCES AS
SELECT
  sds.DEFINITION_SOURCE_ID,
  sds.MODEL_ID,
  m.MODEL_NAME,
  sds.VERSION_ID,
  mv.VERSION_NUMBER,
  sds.SOURCE_KIND,
  sds.SOURCE_NAME,
  sds.DEFINITION_SQL,
  sds.NORMALIZED_JSON,
  sds.DEFINITION_HASH,
  sds.APPLY_STATUS,
  sds.VALIDATION_RUN_ID,
  sds.CREATED_AT,
  sds.CREATED_BY
FROM SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES sds
LEFT JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = sds.MODEL_ID
LEFT JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = sds.VERSION_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_INPUTS AS
SELECT
  mi.METRIC_ID,
  mt.METRIC_NAME,
  mt.MODEL_ID,
  m.MODEL_NAME,
  mt.VERSION_ID,
  mv.VERSION_NUMBER,
  mi.INPUT_ROLE,
  mi.INPUT_OBJECT_TYPE,
  mi.INPUT_OBJECT_ID,
  COALESCE(f.FACT_NAME, dep_mt.METRIC_NAME, d.DIMENSION_NAME, e.ENTITY_NAME) AS INPUT_OBJECT_NAME,
  mi.EXPRESSION_ALIAS,
  mi.OFFSET_WINDOW,
  mi.FILTER_EXPR,
  mi.ORDINAL_POSITION
FROM SYS_SEMANTIC.METRIC_INPUTS mi
JOIN SYS_SEMANTIC.METRICS mt
  ON mt.METRIC_ID = mi.METRIC_ID
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mt.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mt.VERSION_ID
LEFT JOIN SYS_SEMANTIC.FACTS f
  ON mi.INPUT_OBJECT_TYPE = 'FACT'
 AND f.FACT_ID = mi.INPUT_OBJECT_ID
LEFT JOIN SYS_SEMANTIC.METRICS dep_mt
  ON mi.INPUT_OBJECT_TYPE = 'METRIC'
 AND dep_mt.METRIC_ID = mi.INPUT_OBJECT_ID
LEFT JOIN SYS_SEMANTIC.DIMENSIONS d
  ON mi.INPUT_OBJECT_TYPE = 'DIMENSION'
 AND d.DIMENSION_ID = mi.INPUT_OBJECT_ID
LEFT JOIN SYS_SEMANTIC.ENTITIES e
  ON mi.INPUT_OBJECT_TYPE = 'ENTITY'
 AND e.ENTITY_ID = mi.INPUT_OBJECT_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_FILTERS AS
SELECT
  mf.METRIC_ID,
  mt.METRIC_NAME,
  mt.MODEL_ID,
  m.MODEL_NAME,
  mt.VERSION_ID,
  mv.VERSION_NUMBER,
  mf.FILTER_KIND,
  mf.FILTER_EXPR,
  mf.RESOLVED_SQL_EXPR,
  mf.REQUIRED_DIMENSION_ID,
  d.DIMENSION_NAME AS REQUIRED_DIMENSION_NAME,
  mf.REQUIRED_ENTITY_ID,
  e.ENTITY_NAME AS REQUIRED_ENTITY_NAME,
  mf.ORDINAL_POSITION
FROM SYS_SEMANTIC.METRIC_FILTERS mf
JOIN SYS_SEMANTIC.METRICS mt
  ON mt.METRIC_ID = mf.METRIC_ID
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mt.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mt.VERSION_ID
LEFT JOIN SYS_SEMANTIC.DIMENSIONS d
  ON d.DIMENSION_ID = mf.REQUIRED_DIMENSION_ID
LEFT JOIN SYS_SEMANTIC.ENTITIES e
  ON e.ENTITY_ID = mf.REQUIRED_ENTITY_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_OVERVIEW AS
SELECT
  mt.METRIC_ID,
  mt.MODEL_ID,
  m.MODEL_NAME,
  mt.VERSION_ID,
  mv.VERSION_NUMBER,
  so.OBJECT_NAME,
  mt.METRIC_NAME,
  mt.DISPLAY_NAME,
  COALESCE(mt.METRIC_KIND, mt.METRIC_TYPE) AS METRIC_KIND,
  mt.METRIC_TYPE,
  be.ENTITY_NAME AS BASE_ENTITY_NAME,
  mt.FORMAT_HINT,
  mt.IS_CERTIFIED,
  mt.IS_PRIVATE,
  mt.OWNER_ROLE,
  mt.DESCRIPTION,
  syn.SYNONYMS,
  sds.DEFINITION_HASH,
  mt.STATUS
FROM SYS_SEMANTIC.METRICS mt
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mt.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mt.VERSION_ID
LEFT JOIN SYS_SEMANTIC.ENTITIES be
  ON be.ENTITY_ID = mt.BASE_ENTITY_ID
LEFT JOIN SYS_SEMANTIC.OBJECT_COLUMNS oc
  ON oc.COLUMN_KIND = 'METRIC'
 AND oc.OBJECT_REF_ID = mt.METRIC_ID
LEFT JOIN SYS_SEMANTIC.SEMANTIC_OBJECTS so
  ON so.OBJECT_ID = oc.OBJECT_ID
LEFT JOIN (
  SELECT MODEL_ID, VERSION_ID, OBJECT_ID, LISTAGG(SYNONYM, ', ') WITHIN GROUP (ORDER BY SYNONYM) AS SYNONYMS
  FROM SYS_SEMANTIC.SYNONYMS
  WHERE OBJECT_TYPE = 'METRIC'
  GROUP BY MODEL_ID, VERSION_ID, OBJECT_ID
) syn
  ON syn.MODEL_ID = mt.MODEL_ID
 AND syn.VERSION_ID = mt.VERSION_ID
 AND syn.OBJECT_ID = mt.METRIC_ID
LEFT JOIN SYS_SEMANTIC.SEMANTIC_DEFINITION_SOURCES sds
  ON sds.DEFINITION_SOURCE_ID = mt.DEFINITION_SOURCE_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_LINEAGE AS
SELECT
  mt.METRIC_ID,
  mt.METRIC_NAME,
  mt.MODEL_ID,
  m.MODEL_NAME,
  mt.VERSION_ID,
  mv.VERSION_NUMBER,
  COALESCE(mi.INPUT_ROLE, md.DEPENDENCY_KIND) AS INPUT_ROLE,
  COALESCE(mi.INPUT_OBJECT_TYPE, md.DEPENDS_ON_OBJECT_TYPE) AS INPUT_OBJECT_TYPE,
  COALESCE(mi.INPUT_OBJECT_ID, md.DEPENDS_ON_OBJECT_ID) AS INPUT_OBJECT_ID,
  COALESCE(f.FACT_NAME, dep_mt.METRIC_NAME, d.DIMENSION_NAME, e.ENTITY_NAME) AS INPUT_OBJECT_NAME,
  mi.ORDINAL_POSITION
FROM SYS_SEMANTIC.METRICS mt
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mt.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mt.VERSION_ID
LEFT JOIN SYS_SEMANTIC.METRIC_INPUTS mi
  ON mi.METRIC_ID = mt.METRIC_ID
LEFT JOIN SYS_SEMANTIC.METRIC_DEPENDENCIES md
  ON md.METRIC_ID = mt.METRIC_ID
 AND mi.METRIC_ID IS NULL
LEFT JOIN SYS_SEMANTIC.FACTS f
  ON COALESCE(mi.INPUT_OBJECT_TYPE, md.DEPENDS_ON_OBJECT_TYPE) = 'FACT'
 AND f.FACT_ID = COALESCE(mi.INPUT_OBJECT_ID, md.DEPENDS_ON_OBJECT_ID)
LEFT JOIN SYS_SEMANTIC.METRICS dep_mt
  ON COALESCE(mi.INPUT_OBJECT_TYPE, md.DEPENDS_ON_OBJECT_TYPE) = 'METRIC'
 AND dep_mt.METRIC_ID = COALESCE(mi.INPUT_OBJECT_ID, md.DEPENDS_ON_OBJECT_ID)
LEFT JOIN SYS_SEMANTIC.DIMENSIONS d
  ON COALESCE(mi.INPUT_OBJECT_TYPE, md.DEPENDS_ON_OBJECT_TYPE) = 'DIMENSION'
 AND d.DIMENSION_ID = COALESCE(mi.INPUT_OBJECT_ID, md.DEPENDS_ON_OBJECT_ID)
LEFT JOIN SYS_SEMANTIC.ENTITIES e
  ON COALESCE(mi.INPUT_OBJECT_TYPE, md.DEPENDS_ON_OBJECT_TYPE) = 'ENTITY'
 AND e.ENTITY_ID = COALESCE(mi.INPUT_OBJECT_ID, md.DEPENDS_ON_OBJECT_ID)
WHERE COALESCE(mi.INPUT_OBJECT_TYPE, md.DEPENDS_ON_OBJECT_TYPE) IS NOT NULL;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_COMPATIBLE_DIMENSIONS AS
SELECT
  mdm.MODEL_ID,
  m.MODEL_NAME,
  mdm.VERSION_ID,
  mv.VERSION_NUMBER,
  so.OBJECT_ID,
  so.OBJECT_NAME,
  mt.METRIC_ID,
  mt.METRIC_NAME,
  d.DIMENSION_ID,
  d.DIMENSION_NAME,
  d.DISPLAY_NAME,
  e.ENTITY_NAME,
  mdm.IS_VALID,
  mdm.REASON_CODE,
  CASE
    WHEN mdm.IS_VALID THEN 'Metric can be grouped or filtered by this dimension.'
    ELSE 'Metric cannot be grouped or filtered by this dimension: ' || mdm.REASON_CODE
  END AS REASON_MESSAGE,
  mdm.RELATIONSHIP_PATH AS JOIN_PATH_NAME,
  mdm.VALIDATION_RUN_ID,
  mdm.UPDATED_AT
FROM SYS_SEMANTIC.METRIC_DIMENSION_MATRIX mdm
JOIN SYS_SEMANTIC.MODELS m
  ON m.MODEL_ID = mdm.MODEL_ID
JOIN SYS_SEMANTIC.MODEL_VERSIONS mv
  ON mv.VERSION_ID = mdm.VERSION_ID
JOIN SYS_SEMANTIC.METRICS mt
  ON mt.METRIC_ID = mdm.METRIC_ID
LEFT JOIN SYS_SEMANTIC.OBJECT_COLUMNS moc
  ON moc.COLUMN_KIND = 'METRIC'
 AND moc.OBJECT_REF_ID = mt.METRIC_ID
LEFT JOIN SYS_SEMANTIC.SEMANTIC_OBJECTS so
  ON so.OBJECT_ID = moc.OBJECT_ID
JOIN SYS_SEMANTIC.DIMENSIONS d
  ON d.DIMENSION_ID = mdm.DIMENSION_ID
JOIN SYS_SEMANTIC.ENTITIES e
  ON e.ENTITY_ID = d.ENTITY_ID;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.METRIC_FILTER_OVERVIEW AS
SELECT
  mf.MODEL_ID,
  mf.MODEL_NAME,
  mf.VERSION_ID,
  mf.VERSION_NUMBER,
  mf.METRIC_ID,
  mf.METRIC_NAME,
  mf.FILTER_KIND,
  mf.FILTER_EXPR,
  mf.RESOLVED_SQL_EXPR,
  mf.REQUIRED_DIMENSION_NAME,
  mf.REQUIRED_ENTITY_NAME,
  mf.ORDINAL_POSITION
FROM SEMANTIC_CATALOG.METRIC_FILTERS mf;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.SEMANTIC_DEFINITION_SOURCE AS
SELECT
  DEFINITION_SOURCE_ID,
  MODEL_ID,
  MODEL_NAME,
  VERSION_ID,
  VERSION_NUMBER,
  SOURCE_KIND,
  SOURCE_NAME,
  DEFINITION_SQL,
  NORMALIZED_JSON,
  DEFINITION_HASH,
  APPLY_STATUS,
  VALIDATION_RUN_ID,
  CREATED_AT,
  CREATED_BY
FROM SEMANTIC_CATALOG.SEMANTIC_DEFINITION_SOURCES;

CREATE OR REPLACE VIEW SEMANTIC_CATALOG.MODEL_ROLE_GRANTS AS
SELECT
  g.GRANT_ID,
  g.MODEL_ID,
  g.MODEL_NAME,
  g.ROLE_NAME,
  g.PUBLISHED_SCHEMA,
  g.GRANTED_AT,
  g.GRANTED_BY,
  g.STATUS
FROM SYS_SEMANTIC.MODEL_ROLE_GRANTS g
WHERE g.STATUS = 'ACTIVE';

-- METRIC_TYPE: additive storage policy used by the compiler join/aggregation planner.
--   Values: SIMPLE (fully additive), FILTERED (conditional aggregate), RATIO (non-additive quotient),
--   DERIVED (formula over other metrics), WINDOW (pre-computed rolling window -- not yet supported).
-- METRIC_KIND: semantic classification used by agents and discovery tools.
--   Values: SIMPLE, FILTERED, RATIO, DERIVED. Mirrors METRIC_TYPE for standard metrics.
--   An older column name for METRIC_TYPE also exists in legacy rows -- use METRIC_KIND for display.
