SELECT MATERIALIZATION_NAME, STATUS
FROM SEMANTIC_CATALOG.MATERIALIZATIONS
WHERE MODEL_NAME = 'sales'
ORDER BY MATERIALIZATION_NAME;

SELECT MATERIALIZATION_NAME, OBJECT_TYPE, OBJECT_NAME, PHYSICAL_COLUMN, ROLLUP_POLICY
FROM SEMANTIC_CATALOG.MATERIALIZATION_COLUMNS
WHERE MODEL_NAME = 'sales'
ORDER BY MATERIALIZATION_NAME, OBJECT_TYPE, OBJECT_NAME;

EXECUTE SCRIPT SEMANTIC_ADMIN.COMPILE_REQUEST_JSON(
  '{"model":"sales","object":"SALES","metrics":["total_revenue"],"dimensions":["customer_region"],"order_by":[{"field":"total_revenue","direction":"desc"}],"limit":2,"client":"materialization_smoke"}'
);

EXECUTE SCRIPT SEMANTIC_ADMIN.COMPILE_SQL(
  'SELECT customer_region, total_revenue FROM SEMANTIC_SALES.SALES GROUP BY customer_region ORDER BY total_revenue DESC LIMIT 2'
);
