EXECUTE SCRIPT SEMANTIC_ADMIN.VALIDATE_MODEL('sales');

SELECT
  MODEL_NAME,
  COUNT(*) AS MATRIX_ROWS,
  SUM(CASE WHEN IS_VALID THEN 1 ELSE 0 END) AS VALID_MATRIX_ROWS
FROM SEMANTIC_CATALOG.METRIC_DIMENSION_MATRIX
WHERE MODEL_NAME = 'sales'
GROUP BY MODEL_NAME;

SELECT
  RULE_CODE,
  COUNT(*) AS ISSUE_COUNT
FROM SEMANTIC_CATALOG.VALIDATION_RESULTS
WHERE MODEL_NAME = 'sales'
GROUP BY RULE_CODE
ORDER BY RULE_CODE;
