DROP SCHEMA IF EXISTS SEMANTIC_SALES CASCADE;
DROP SCHEMA IF EXISTS SEMANTIC_AGENT CASCADE;
DROP SCHEMA IF EXISTS SEMANTIC_CATALOG CASCADE;
DROP SCHEMA IF EXISTS SEMANTIC_ADMIN CASCADE;
DROP SCHEMA IF EXISTS SYS_SEMANTIC CASCADE;
DROP SCHEMA IF EXISTS MART CASCADE;
